/* =====================================================================
   worlds.js — lumile 2–10: 90 de camere generate din „rețete”.
   Fiecare cameră are: nume, poveste, tipurile de probe potrivite (pool),
   rețeta scenei (vezi scenegen.js), 6 cuvinte tematice pentru anagrame și
   mesaje cifrate (litere mari, fără diacritice) și 3 curiozități.
   Lumea 1 (cele 10 camere desenate manual) este definită în rooms.js.
   ===================================================================== */
(function (global) {
  'use strict';

  /* rețetă de scenă, scrisă compact */
  function sc(wall, wc, floor, fc, light, door, accent, accent2, wood, metal, objects, sky, flip) {
    return { wall: { style: wall, colors: wc }, floor: { style: floor, colors: fc }, light: light, door: door,
             accent: accent, accent2: accent2, wood: wood, metal: metal, objects: objects, sky: sky || 'day', flip: !!flip };
  }
  function r(id, name, sub, emoji, target, story, pool, scene, words, facts) {
    return { id: id, name: name, sub: sub, emoji: emoji, target: target, story: story, pool: pool, scene: scene, words: words, facts: facts };
  }

  var WORLDS = [
    { id: 'clasic', name: 'Lumea Clasică', emoji: '🗝️', desc: 'Cele zece camere de la început', rooms: null },

    /* ================================================================
       LUMEA 2 — ORAȘUL NOSTRU
       ================================================================ */
    { id: 'oras', name: 'Orașul Nostru', emoji: '🏙️', desc: 'Locuri pe care le știi din fiecare zi', rooms: [
      r('bucatarie', 'Bucătăria Bunicii', 'Miroase a plăcinte', '🥧', 300,
        'Bunica a plecat la piață și ușa s-a blocat cu tine înăuntru. Cele <b>{n} rețete secrete</b> ascunse prin bucătărie îți dau codul ieșirii.',
        ['math', 'money', 'count', 'riddle', 'culture', 'clock', 'weights', 'sliders', 'match'],
        sc('tiles', ['#fef3c7', '#fde68a', '#fbbf24'], 'checker', ['#b45309', '#78350f'], 'windows', 'wood', '#dc2626', '#16a34a', '#a16207', '#94a3b8',
           [['oale', 'Oalele agățate'], ['soba', 'Soba veche'], ['raft', 'Raftul cu borcane'], ['ceainic', 'Ceainicul']]),
        [['OALA', 'Fierbe supa în ea'], ['LINGURA', 'Mănânci supa cu ea'], ['PAINE', 'Se coace din făină'], ['SUPA', 'Ciorbă fierbinte'], ['FARFURIE', 'Pui mâncarea pe ea'], ['CUPTOR', 'Coace prăjiturile']],
        ['O plăcintă se coace mai repede dacă tava e pusă la mijlocul cuptorului, nu jos.', 'Ceapa te face să plângi pentru că eliberează un gaz care irită ochii — o poți ține în frigider înainte de tăiere.', 'Un ou stă pe fundul paharului cu apă dacă e proaspăt și plutește dacă e vechi.']),
      r('garaj', 'Garajul lui Tata', 'Unelte, uleiuri și roți', '🔧', 300,
        'Ușa garajului s-a blocat pe jumătate. Ca să pornești motorul de ridicare trebuie să rezolvi <b>{n} probe mecanice</b>.',
        ['math', 'count', 'sequence', 'logic', 'sliders', 'dial', 'shapes', 'order', 'weights'],
        sc('metal', ['#9ca3af', '#6b7280', '#4b5563'], 'plain', ['#57534e', '#292524'], 'lamp', 'garage', '#f59e0b', '#0ea5e9', '#92400e', '#9ca3af',
           [['unelte', 'Panoul cu unelte'], ['bicicleta', 'Bicicleta'], ['semn', 'Indicatorul'], ['cutii', 'Cutiile cu piese']]),
        [['ROATA', 'Se învârte sub mașină'], ['CHEIE', 'Strânge șuruburile'], ['MOTOR', 'Pune mașina în mișcare'], ['ULEI', 'Unge piesele'], ['CIOCAN', 'Bate cuiele'], ['SURUB', 'Se răsucește cu șurubelnița']],
        ['Pneul unei mașini are un desen cu caneluri ca să scoată apa de sub el pe ploaie.', 'O bicicletă stă în echilibru mai ușor când merge repede decât când stă pe loc.', 'Cheile de la mașină moderne conțin un mic cip care „vorbește” cu mașina.']),
      r('brutarie', 'Brutăria de la Colț', 'Pâine caldă și covrigi', '🥖', 300,
        'Brutarul a uitat să stingă cuptorul și ușa s-a înțepenit de la abur. Rezolvă <b>{n} probe</b> ca să deschizi ușa cu clopoțel.',
        ['math', 'money', 'count', 'weights', 'clock', 'shapes', 'riddle', 'match', 'sliders'],
        sc('bricks', ['#d97706', '#b45309', '#92400e'], 'tiles', ['#a8a29e', '#57534e'], 'windows', 'glass', '#ea580c', '#fbbf24', '#a16207', '#94a3b8',
           [['tabla', 'Tabla cu prețuri'], ['soba', 'Cuptorul'], ['ceas', 'Ceasul'], ['carucior', 'Căruciorul cu făină']]),
        [['COVRIG', 'Rotund, cu susan'], ['FAINA', 'Praf alb din grâu'], ['ALUAT', 'Se frământă'], ['CORN', 'Chiflă în formă de semilună'], ['DROJDIE', 'Face aluatul să crească'], ['BRUTAR', 'Coace pâinea']],
        ['Pâinea crește pentru că drojdia „respiră” și umflă aluatul cu bule mici.', 'Coaja pâinii e maronie pentru că zahărul din aluat se rumenește la căldură.', 'Brutarii încep lucrul noaptea, ca pâinea să fie caldă dimineața.']),
      r('pompieri', 'Stația de Pompieri', 'Alarmă și furtunuri', '🚒', 320,
        'Alarma a pornit și porțile stației s-au blocat. Pompierii au lăsat <b>{n} teste de curaj</b> pentru cine vrea să iasă.',
        ['math', 'count', 'sequence', 'culture', 'logic', 'order', 'dial', 'sliders', 'clock'],
        sc('bricks', ['#b91c1c', '#991b1b', '#7f1d1d'], 'metal', ['#6b7280', '#374151'], 'lamp', 'garage', '#dc2626', '#fbbf24', '#7c2d12', '#9ca3af',
           [['clopot', 'Clopotul de alarmă'], ['hidrant', 'Hidrantul'], ['dulapior', 'Trusa de prim ajutor'], ['unelte', 'Uneltele pompierilor']]),
        [['FOC', 'Îl sting pompierii'], ['APA', 'Curge din furtun'], ['CASCA', 'Apără capul'], ['SCARA', 'Urcă la etaj'], ['SIRENA', 'Sună tare pe drum'], ['FURTUN', 'Prin el țâșnește apa']],
        ['Numărul de urgență 112 funcționează în toată Europa, chiar și fără credit pe telefon.', 'Într-un incendiu, fumul urcă — de aceea te apleci și mergi cât mai jos.', 'Hainele pompierilor rezistă la temperaturi de sute de grade.']),
      r('gara', 'Gara Veche', 'Trenul pleacă la fix', '🚉', 320,
        'Ultimul tren pleacă în câteva minute, dar sala de așteptare e încuiată. <b>Găsește codul șefului de gară</b> înainte de fluier!',
        ['math', 'clock', 'sequence', 'order', 'count', 'money', 'logic', 'dial', 'riddle'],
        sc('panels', ['#a8a29e', '#78716c', '#57534e'], 'tiles', ['#a3a3a3', '#525252'], 'lamp', 'glass', '#166534', '#f59e0b', '#7c4a1e', '#9ca3af',
           [['ceas', 'Ceasul gării'], ['valiza', 'Valiza uitată'], ['semn', 'Indicatorul peroanelor'], ['carucior', 'Căruciorul de bagaje']]),
        [['TREN', 'Merge pe șine'], ['BILET', 'Îl arăți conductorului'], ['PERON', 'Aștepți trenul pe el'], ['SINA', 'Pe ea rulează roțile'], ['VAGON', 'Stau călătorii în el'], ['VALIZA', 'Îți duci hainele în ea']],
        ['Ceasurile din gări arată toate exact aceeași oră, ca trenurile să nu plece greșit.', 'Trenul frânează pe o distanță foarte lungă — nu traversa niciodată calea ferată când vine.', 'Prima cale ferată din România a fost construită acum peste 150 de ani.']),
      r('supermarket', 'Supermarketul', 'Rafturi, prețuri și coșuri', '🛒', 320,
        'Magazinul s-a închis cu tine înăuntru! Casele de marcat îți dau codul ușii glisante dacă rezolvi <b>{n} probleme cu prețuri</b>.',
        ['money', 'math', 'count', 'weights', 'order', 'match', 'logic', 'sliders', 'shapes'],
        sc('dots', ['#e0f2fe', '#bae6fd', '#7dd3fc'], 'checker', ['#e5e7eb', '#9ca3af'], 'neon', 'glass', '#ef4444', '#22c55e', '#7c4a1e', '#94a3b8',
           [['carucior', 'Coșul de cumpărături'], ['lada_fructe', 'Lada cu fructe'], ['raft', 'Raftul cu conserve'], ['cadran', 'Cântarul']]),
        [['PRET', 'Scris pe etichetă'], ['REST', 'Banii primiți înapoi'], ['LAPTE', 'Alb, de la vacă'], ['MAR', 'Fruct roșu sau verde'], ['CASIER', 'Îți încasează banii'], ['REDUCERE', 'Prețul scade']],
        ['Produsele cele mai scumpe stau de obicei la nivelul ochilor, iar cele ieftine jos sau sus.', 'Fructele coapte se pun deasupra celor tari, ca să nu se strivească.', 'Codul de bare cu dungi e citit de o rază de lumină în mai puțin de o secundă.']),
      r('scoala', 'Sala de Clasă', 'Tabla, catedra, clopoțelul', '🎒', 300,
        'Clopoțelul a sunat, dar ușa clasei nu se deschide. Doamna învățătoare a lăsat <b>{n} exerciții-surpriză</b> pentru cine vrea în pauză.',
        ['math', 'riddle', 'culture', 'anagram', 'cipher', 'sequence', 'shapes', 'clock', 'proverb'],
        sc('panels', ['#bbf7d0', '#86efac', '#4ade80'], 'planks', ['#a16207', '#713f12'], 'windows', 'wood', '#2563eb', '#f59e0b', '#a16207', '#94a3b8',
           [['tabla', 'Tabla'], ['birou', 'Catedra'], ['calendar', 'Calendarul'], ['glob', 'Globul pământesc']]),
        [['CRETA', 'Scrie pe tablă'], ['CAIET', 'Scrii temele în el'], ['BANCA', 'Stai în ea la ore'], ['PIX', 'Scrie cu pastă'], ['GHIOZDAN', 'Îl porți în spate'], ['PAUZA', 'Timp de joacă între ore']],
        ['Creta e făcută din scoici și cochilii de animale marine mărunțite acum milioane de ani.', 'Creierul ține minte mai bine dacă înveți puțin în fiecare zi decât mult într-o singură zi.', 'Ghiozdanul nu ar trebui să cântărească mai mult de o zecime din greutatea ta.']),
      r('doctor', 'Cabinetul Doctorului', 'Pansamente și termometre', '🩺', 320,
        'Ai venit la control, dar cabinetul s-a încuiat automat. Rezolvă <b>{n} teste de sănătate</b> și ușa se deschide.',
        ['math', 'count', 'culture', 'weights', 'clock', 'logic', 'match', 'sliders', 'dial'],
        sc('tiles', ['#e0f2fe', '#bae6fd', '#93c5fd'], 'plain', ['#cbd5e1', '#64748b'], 'lamp', 'glass', '#ef4444', '#0ea5e9', '#a16207', '#94a3b8',
           [['dulapior', 'Dulăpiorul cu medicamente'], ['cadran', 'Cântarul'], ['afis', 'Afișul de pe perete'], ['ecran', 'Monitorul']]),
        [['INIMA', 'Bate în piept'], ['DINTE', 'Îl speli seara'], ['OS', 'Tare, în interiorul corpului'], ['PULS', 'Îl simți la încheietură'], ['PLASTURE', 'Îl pui pe o zgârietură'], ['VITAMINA', 'Se găsește în fructe']],
        ['Inima unui copil bate cam de 90 de ori pe minut, mai repede decât a unui adult.', 'Când ai febră, corpul se încălzește ca să lupte cu microbii.', 'Spălatul pe mâini cu săpun oprește mai multe boli decât orice medicament.']),
      r('posta', 'Oficiul Poștal', 'Scrisori, timbre și colete', '✉️', 300,
        'Poștașul a plecat cu cheia în buzunar. Coletele de pe rafturi ascund <b>{n} mesaje</b> — descifrează-le și ieși.',
        ['cipher', 'anagram', 'math', 'count', 'order', 'money', 'weights', 'match', 'logic'],
        sc('panels', ['#fde68a', '#fcd34d', '#f59e0b'], 'tiles', ['#a8a29e', '#57534e'], 'windows', 'wood', '#2563eb', '#dc2626', '#92400e', '#94a3b8',
           [['cutie_postala', 'Cutia poștală'], ['harta', 'Harta orașului'], ['cutii', 'Coletele'], ['calendar', 'Calendarul cu ștampile']]),
        [['TIMBRU', 'Se lipește pe plic'], ['PLIC', 'Scrisoarea stă în el'], ['COLET', 'Pachet trimis prin poștă'], ['POSTAS', 'Aduce scrisorile'], ['ADRESA', 'Strada și numărul'], ['SCRISOARE', 'O trimiți unui prieten']],
        ['Fiecare localitate are un cod poștal — șase cifre care spun exact unde ajunge plicul.', 'Cel mai vechi timbru din lume, „Penny Black”, are peste 180 de ani.', 'Un colet poate face înconjurul lumii în mai puțin de o săptămână.']),
      r('parc', 'Parcul de Joacă', 'Leagăne, baloane și mingi', '🛝', 300,
        'Portarul a închis poarta parcului cu tine înăuntru! Prin parc sunt ascunse <b>{n} jocuri</b> care îți dau codul lacătului.',
        ['count', 'math', 'shapes', 'sequence', 'riddle', 'logic', 'order', 'match', 'weights'],
        sc('plain', ['#7dd3fc', '#bae6fd', '#86efac'], 'grass', ['#4ade80', '#15803d'], 'sun', 'gate', '#f472b6', '#facc15', '#92400e', '#9ca3af',
           [['mingi', 'Mingile'], ['baloane', 'Baloanele'], ['cos_flori', 'Coșul cu flori'], ['fantana', 'Fântâna']]),
        [['LEAGAN', 'Te dai în el'], ['MINGE', 'Sare și se rostogolește'], ['BANCA', 'Stai pe ea în parc'], ['IARBA', 'Verde, sub picioare'], ['TOBOGAN', 'Aluneci pe el'], ['ZMEU', 'Zboară pe sfoară']],
        ['Nisipul din parc e ales special: boabele rotunde nu zgârie și se scutură ușor.', 'Un leagăn merge mai sus dacă îți întinzi picioarele când urci și le strângi când cobori.', 'Copacii dintr-un parc răcoresc aerul cu câteva grade în zilele fierbinți.'])
    ] },

    /* ================================================================
       LUMEA 3 — NATURA SĂLBATICĂ
       ================================================================ */
    { id: 'natura', name: 'Natura Sălbatică', emoji: '🌿', desc: 'Ferme, păduri, peșteri și insule', rooms: [
      r('ferma', 'Ferma Veselă', 'Găini, vaci și un hambar', '🐄', 300,
        'Ai intrat în hambar după pui, iar vântul a trântit ușa. Animalele știu codul — rezolvă <b>{n} probe</b> ca să ți-l spună.',
        ['count', 'math', 'riddle', 'match', 'weights', 'logic', 'order', 'sequence', 'money'],
        sc('planks', ['#b45309', '#92400e', '#78350f'], 'sand', ['#d6b370', '#a16207'], 'windows', 'wood', '#dc2626', '#22c55e', '#a16207', '#94a3b8',
           [['sperietoare', 'Sperietoarea'], ['lada_fructe', 'Lada cu legume'], ['butoi', 'Butoiul'], ['carucior', 'Roaba']]),
        [['VACA', 'Dă lapte'], ['OAIE', 'Are lână'], ['PUI', 'Copilul găinii'], ['CAL', 'Aleargă și nechează'], ['FERMIER', 'Îngrijește animalele'], ['HAMBAR', 'Aici se ține fânul']],
        ['O vacă bea într-o zi cât o cadă plină cu apă.', 'Găinile pot ține minte fețele a peste 100 de alte găini.', 'Porcii nu transpiră, de aceea se tăvălesc în noroi ca să se răcorească.']),
      r('padure', 'Cabana din Pădure', 'Liniște, brazi și un foc', '🌲', 320,
        'Furtuna a doborât un copac în fața cabanei. Pădurarul a lăsat <b>{n} semne</b> care duc la cheia ieșirii din spate.',
        ['riddle', 'count', 'math', 'anagram', 'logic', 'match', 'sequence', 'weights', 'culture'],
        sc('planks', ['#6b4423', '#4a2e14', '#2f1b0c'], 'planks', ['#5c3a1e', '#2f1b0c'], 'candles', 'wood', '#16a34a', '#f59e0b', '#7c4a1e', '#78716c',
           [['coarne', 'Trofeul cu coarne'], ['soba', 'Soba de fontă'], ['harta', 'Harta pădurii'], ['cufar', 'Cufărul pădurarului']], 'night'),
        [['BRAD', 'Verde tot anul'], ['LUP', 'Urlă la lună'], ['URS', 'Doarme iarna'], ['CIUPERCA', 'Are pălărie'], ['VEVERITA', 'Adună alune'], ['CARARE', 'Drum îngust prin pădure']],
        ['Dacă te rătăcești în pădure, rămâi pe loc — ești găsit mai ușor decât dacă mergi la întâmplare.', 'Mușchiul crește mai des pe partea de nord a copacilor, unde e mai umbră.', 'Un copac mare eliberează într-o zi oxigen pentru mai mulți oameni.']),
      r('stupina', 'Stupina', 'Bâzâit și miere', '🐝', 300,
        'Apicultorul a plecat cu costumul de protecție, iar albinele păzesc gardul. Rezolvă <b>{n} probe dulci</b> și ele îți deschid poarta.',
        ['count', 'math', 'shapes', 'sequence', 'riddle', 'weights', 'money', 'match', 'logic'],
        sc('plain', ['#fde68a', '#fcd34d', '#f59e0b'], 'grass', ['#86efac', '#16a34a'], 'sun', 'gate', '#f59e0b', '#78350f', '#a16207', '#9ca3af',
           [['borcan', 'Borcanul cu miere'], ['cutii', 'Stupii de lemn'], ['cos_flori', 'Florile'], ['semn', 'Indicatorul']]),
        [['MIERE', 'Dulce, făcută de albine'], ['STUP', 'Casa albinelor'], ['FAGURE', 'Are celule hexagonale'], ['FLOARE', 'Albina ia nectar din ea'], ['POLEN', 'Praf galben din flori'], ['REGINA', 'Albina cea mai mare']],
        ['Celulele fagurelui au șase laturi pentru că așa nu rămâne niciun spațiu gol.', 'O albină face în toată viața ei doar o linguriță de miere.', 'Albinele „dansează” ca să le spună celorlalte unde sunt florile.']),
      r('pestera', 'Peștera Liliecilor', 'Întuneric și picături', '🦇', 340,
        'O stâncă s-a prăbușit peste intrare. Liliecii nu te deranjează, dar ieșirea secretă cere <b>{n} probe</b> rezolvate în beznă.',
        ['count', 'math', 'logic', 'sequence', 'cipher', 'shapes', 'riddle', 'dial', 'weights'],
        sc('cave', ['#57534e', '#44403c', '#1c1917'], 'stone', ['#44403c', '#1c1917'], 'torches', 'cave', '#a78bfa', '#38bdf8', '#57534e', '#78716c',
           [['cristal', 'Cristalele'], ['panza', 'Pânza de păianjen'], ['foc', 'Focul de tabără'], ['ou', 'Oul misterios']]),
        [['LILIAC', 'Zboară noaptea, doarme cu capul în jos'], ['STANCA', 'Piatră mare'], ['ECOU', 'Sunetul care se întoarce'], ['BEZNA', 'Întuneric total'], ['TORTA', 'Luminează peștera'], ['PICATURA', 'Cade din tavan']],
        ['Liliecii nu sunt orbi — dar noaptea „văd” cu ajutorul sunetelor, ca un sonar.', 'Stalactitele cresc din tavan cam cât un fir de păr într-un an.', 'În peșteri temperatura e aceeași vara și iarna.']),
      r('vulcan', 'Vulcanul Adormit', 'Lavă, fum și cristale', '🌋', 340,
        'Cercetătorii au fugit când muntele a bubuit, iar ușa buncărului s-a închis. <b>Repornește aparatele</b> ca să deblochezi ieșirea.',
        ['math', 'sequence', 'count', 'logic', 'dial', 'sliders', 'shapes', 'cipher', 'order'],
        sc('cave', ['#7f1d1d', '#450a0a', '#1c1917'], 'stone', ['#44403c', '#1c1917'], 'none', 'stone', '#f97316', '#facc15', '#57534e', '#78716c',
           [['cadran', 'Seismograful'], ['cristal', 'Cristalele de lavă'], ['cazan', 'Cazanul cu lavă'], ['cutii', 'Lăzile cercetătorilor']]),
        [['LAVA', 'Piatră topită, roșie'], ['FUM', 'Iese din crater'], ['CRATER', 'Gaura din vârful vulcanului'], ['MAGMA', 'Lava de sub pământ'], ['CENUSA', 'Praf gri după erupție'], ['ERUPTIE', 'Când vulcanul se trezește']],
        ['Lava e atât de fierbinte încât topește pietrele — de peste zece ori mai fierbinte decât apa care fierbe.', 'Pe Pământ sunt aproape 1500 de vulcani care mai pot erupe.', 'Pământul din jurul vulcanilor e foarte bun pentru grădini, de aceea oamenii locuiesc aproape de ei.']),
      r('insula', 'Insula Pustie', 'Nisip, palmieri și o epavă', '🏝️', 320,
        'Barca ta a plecat fără tine! Pe plajă sunt <b>{n} indicii</b> lăsate de un naufragiat — ele deschid barca de salvare.',
        ['count', 'math', 'riddle', 'cipher', 'anagram', 'logic', 'shapes', 'sequence', 'match'],
        sc('plain', ['#7dd3fc', '#bae6fd', '#fde68a'], 'sand', ['#fde68a', '#d6b370'], 'sun', 'vine', '#0ea5e9', '#f97316', '#a16207', '#78716c',
           [['cort', 'Cortul'], ['foc', 'Focul de semnal'], ['cufar', 'Cufărul eșuat'], ['ancora', 'Ancora ruginită']]),
        [['NISIP', 'Fin și galben pe plajă'], ['VAL', 'Vine și pleacă'], ['SCOICA', 'O găsești pe plajă'], ['CRAB', 'Merge într-o parte'], ['PALMIER', 'Copac cu nuci de cocos'], ['PLUTA', 'Barcă din bușteni']],
        ['Nuca de cocos plutește, așa că palmierii ajung pe insule noi purtați de mare.', 'Apa mării nu se bea: sarea din ea te face și mai însetat.', 'Un foc de semnal se vede mai bine ziua dacă îi pui frunze verzi, ca să scoată fum alb.']),
      r('lac', 'Lacul cu Nuferi', 'Broaște, libelule și ceață', '🪷', 300,
        'Barca pescarului s-a împotmolit în nuferi. Ca să găsești vâslele ascunse, rezolvă <b>{n} probe de pe mal</b>.',
        ['count', 'riddle', 'math', 'sequence', 'shapes', 'match', 'logic', 'weights', 'order'],
        sc('plain', ['#0f766e', '#115e59', '#134e4a'], 'water', ['#0e7490', '#164e63'], 'moon', 'gate', '#f472b6', '#4ade80', '#7c4a1e', '#78716c',
           [['cort', 'Cortul pescarului'], ['borcan', 'Borcanul cu licurici'], ['ceainic', 'Ceainicul de la foc'], ['foc', 'Focul de pe mal']], 'night'),
        [['NUFAR', 'Floare care plutește'], ['BARCA', 'Plutește pe lac'], ['PESTE', 'Înoată în apă'], ['MAL', 'Marginea lacului'], ['BROASCA', 'Sare și orăcăie'], ['LIBELULA', 'Insectă cu aripi transparente']],
        ['Frunza de nufăr e atât de mare la unele specii încât poate ține un copil pe ea.', 'Broaștele beau apă prin piele, nu cu gura.', 'Licuricii aprind și sting lumina ca să se salute unii pe alții.']),
      r('munte', 'Refugiul de pe Munte', 'Zăpadă și ceai fierbinte', '⛰️', 320,
        'Viscolul a blocat ușa refugiului. Salvamontiștii au lăsat <b>{n} probe</b> pentru cine vrea să coboare în siguranță.',
        ['math', 'count', 'culture', 'clock', 'sequence', 'weights', 'logic', 'riddle', 'dial'],
        sc('stone', ['#9ca3af', '#6b7280', '#4b5563'], 'planks', ['#7c4a1e', '#3f2107'], 'windows', 'wood', '#dc2626', '#38bdf8', '#7c4a1e', '#9ca3af',
           [['harta', 'Harta traseelor'], ['sanie', 'Sania'], ['soba', 'Soba'], ['dulapior', 'Trusa de prim ajutor']], 'snow'),
        [['VARF', 'Partea cea mai de sus a muntelui'], ['ZAPADA', 'Albă și rece'], ['CABANA', 'Casă de lemn la munte'], ['TRASEU', 'Drum marcat prin munți'], ['BOCANC', 'Încălțăminte de munte'], ['RUCSAC', 'Îl porți în spate']],
        ['La munte aerul e mai rece cu un grad la fiecare 150 de metri urcați.', 'Marcajele de pe copaci (dungă colorată între două albe) îți arată traseul.', 'Zăpada proaspătă e formată mai mult din aer decât din apă.']),
      r('desert', 'Oaza din Deșert', 'Dune, cămile și un puț', '🏜️', 320,
        'Caravana a plecat în zori și cortul tău a rămas legat. <b>Găsește codul</b> lăsat de cămilar în cele {n} locuri din oază.',
        ['math', 'count', 'riddle', 'cipher', 'logic', 'money', 'weights', 'sequence', 'order'],
        sc('plain', ['#fbbf24', '#f59e0b', '#d97706'], 'sand', ['#fde68a', '#d6b370'], 'sun', 'curtain', '#dc2626', '#0ea5e9', '#a16207', '#9ca3af',
           [['cactus', 'Cactusul'], ['vaza', 'Urciorul cu apă'], ['cort', 'Cortul beduinului'], ['cufar', 'Cufărul caravanei']]),
        [['DUNA', 'Deal de nisip'], ['CAMILA', 'Are cocoașe'], ['OAZA', 'Loc cu apă în deșert'], ['SOARE', 'Arde tare la amiază'], ['CACTUS', 'Plantă cu țepi'], ['CARAVANA', 'Șir de cămile']],
        ['Cămila nu ține apă în cocoașe, ci grăsime — din ea își ia energie când nu are ce mânca.', 'În deșert e foarte cald ziua, dar noaptea poate fi frig ca iarna.', 'Cactușii au țepi în loc de frunze ca să nu piardă apă.']),
      r('delta', 'Coliba din Deltă', 'Stuf, pelicani și bărci', '🐦', 320,
        'Barca a plecat pe canal fără tine, iar coliba pescarului are un lacăt ciudat. Cele <b>{n} probe</b> de pe pontonul de lemn îl deschid.',
        ['count', 'riddle', 'math', 'match', 'culture', 'sequence', 'logic', 'weights', 'shapes'],
        sc('bamboo', ['#a3a3a3', '#78716c', '#57534e'], 'water', ['#0e7490', '#155e75'], 'windows', 'wood', '#f97316', '#22c55e', '#a16207', '#78716c',
           [['ancora', 'Ancora bărcii'], ['acvariu', 'Acvariul cu peștișori'], ['harta', 'Harta canalelor'], ['ceainic', 'Ceainicul pescarului']], 'sunset'),
        [['STUF', 'Plantă înaltă de la baltă'], ['PELICAN', 'Pasăre cu cioc uriaș'], ['CANAL', 'Drum de apă'], ['BARCA', 'Merge pe apă'], ['PLASA', 'Prinde pești'], ['DUNARE', 'Fluviul care ajunge în deltă']],
        ['Delta Dunării crește în fiecare an cu câțiva metri, din nisipul adus de fluviu.', 'Pelicanul poate ține în cioc mai multă apă decât încape în burta lui.', 'Casele din deltă au acoperiș din stuf, care ține cald iarna și răcoare vara.'])
    ] },

    /* ================================================================
       LUMEA 4 — ATELIERE ȘI MESERII
       ================================================================ */
    { id: 'meserii', name: 'Ateliere și Meserii', emoji: '🛠️', desc: 'Fierari, olari, croitori și cofetari', rooms: [
      r('fierarie', 'Fierăria', 'Foc, nicovală și scântei', '🔨', 320,
        'Fierarul a plecat după cărbuni și a tras zăvorul. Potcoavele de pe perete ascund <b>{n} probe</b> — rezolvă-le și zăvorul cade.',
        ['math', 'weights', 'count', 'shapes', 'sequence', 'dial', 'sliders', 'logic', 'order'],
        sc('stone', ['#57534e', '#44403c', '#292524'], 'stone', ['#44403c', '#1c1917'], 'torches', 'metal', '#f97316', '#fbbf24', '#7c4a1e', '#9ca3af',
           [['nicovala', 'Nicovala'], ['soba', 'Forja'], ['unelte', 'Uneltele'], ['butoi', 'Butoiul cu apă']]),
        [['FIER', 'Metal tare și greu'], ['FOC', 'Încălzește fierul'], ['CIOCAN', 'Bate pe nicovală'], ['POTCOAVA', 'O poartă calul'], ['CLESTE', 'Ține fierul fierbinte'], ['SCANTEIE', 'Sare când bați fierul']],
        ['Fierul se înmoaie când e încălzit până devine roșu-portocaliu și atunci poate fi îndoit.', 'Potcoavele apără copitele cailor ca pantofii tălpile noastre.', 'Fierul ruginește dacă stă în apă, de aceea uneltele se ung cu ulei.']),
      r('olarie', 'Olăria', 'Lut, roată și cuptor', '🏺', 300,
        'Olarul a lăsat cuptorul aprins și a plecat la târg. Rezolvă <b>{n} probe</b> printre vasele de lut ca să scoți zăvorul.',
        ['shapes', 'count', 'math', 'sequence', 'order', 'weights', 'riddle', 'match', 'dial'],
        sc('bricks', ['#d6b370', '#b8955a', '#8b6a3a'], 'tiles', ['#a8a29e', '#57534e'], 'windows', 'wood', '#c2410c', '#0ea5e9', '#a16207', '#78716c',
           [['roata', 'Roata olarului'], ['vaza', 'Vaza cea mare'], ['raft', 'Raftul cu vase'], ['soba', 'Cuptorul de ars']]),
        [['LUT', 'Pământ moale, se modelează'], ['VAS', 'Ține apă sau flori'], ['ROATA', 'Se învârte sub vas'], ['OLAR', 'Face vase din lut'], ['CANA', 'Bei ceai din ea'], ['CUPTOR', 'Arde vasele ca să fie tari']],
        ['Vasele de lut se ard la peste 900 de grade ca să nu se mai înmoaie în apă.', 'Olăritul e una dintre cele mai vechi meserii: s-au găsit vase vechi de 20.000 de ani.', 'Apa dintr-un urcior de lut rămâne rece pentru că vasul „transpiră” ușor.']),
      r('croitorie', 'Atelierul Croitorului', 'Ace, ață și stofe', '🧵', 300,
        'Croitorul a închis atelierul cu tine la probă! Manechinele știu codul — rezolvă <b>{n} probe</b> ca să-l afli.',
        ['math', 'count', 'shapes', 'order', 'match', 'sequence', 'logic', 'money', 'weights'],
        sc('dots', ['#fce7f3', '#fbcfe8', '#f9a8d4'], 'planks', ['#a16207', '#713f12'], 'lamp', 'wood', '#be185d', '#0ea5e9', '#92400e', '#94a3b8',
           [['oglinda', 'Oglinda mare'], ['dulap', 'Dulapul cu stofe'], ['masa', 'Masa de croit'], ['afis', 'Afișul cu modele']]),
        [['AC', 'Mic și ascuțit, cu ață'], ['ATA', 'Fir subțire de cusut'], ['NASTURE', 'Închide haina'], ['STOFA', 'Material pentru haine'], ['FOARFECA', 'Taie materialul'], ['ROCHIE', 'O poartă fetele']],
        ['Un croitor bun ia măsura de două ori și taie o singură dată.', 'Prima mașină de cusut a fost inventată acum aproape 200 de ani.', 'Degetarul apără degetul de înțepături când împingi acul.']),
      r('pictor', 'Atelierul Pictorului', 'Pensule, culori și șevalete', '🎨', 300,
        'Pictorul a plecat după inspirație și a încuiat atelierul. Tablourile de pe pereți ascund <b>{n} probe colorate</b>.',
        ['shapes', 'count', 'math', 'sequence', 'match', 'riddle', 'logic', 'order', 'culture'],
        sc('plain', ['#f5f5f4', '#e7e5e4', '#d6d3d1'], 'planks', ['#a8a29e', '#57534e'], 'windows', 'wood', '#7c3aed', '#f59e0b', '#a16207', '#94a3b8',
           [['tablou', 'Tabloul neterminat'], ['portret', 'Portretul'], ['vaza', 'Vaza cu pensule'], ['lampadar', 'Lampa de atelier']]),
        [['PENSULA', 'Pictezi cu ea'], ['ROSU', 'Culoarea macului'], ['VERDE', 'Culoarea ierbii'], ['RAMA', 'Înconjoară tabloul'], ['PALETA', 'Amesteci culorile pe ea'], ['PORTRET', 'Tablou cu o față']],
        ['Din roșu, galben și albastru poți obține aproape orice altă culoare.', 'Culorile calde (roșu, portocaliu) par mai aproape, iar cele reci (albastru) par mai departe.', 'Unii pictori din vechime își făceau singuri culorile din pietre și plante pisate.']),
      r('tipografie', 'Tipografia', 'Litere de plumb și cerneală', '📰', 320,
        'Presa tipografică s-a oprit cu un scârțâit și ușa de fier s-a blocat. <b>Culege literele potrivite</b> în cele {n} probe și presa repornește.',
        ['anagram', 'cipher', 'math', 'count', 'order', 'sequence', 'logic', 'match', 'proverb'],
        sc('bricks', ['#78716c', '#57534e', '#44403c'], 'metal', ['#6b7280', '#374151'], 'lamp', 'metal', '#dc2626', '#0ea5e9', '#7c4a1e', '#9ca3af',
           [['birou', 'Biroul cu litere'], ['cutii', 'Cutiile cu ziare'], ['panou', 'Mașina de tipărit'], ['calendar', 'Calendarul']]),
        [['LITERA', 'Semn din alfabet'], ['ZIAR', 'Apare în fiecare zi'], ['CARTE', 'Are pagini și coperți'], ['TITLU', 'Scris mare, deasupra textului'], ['CERNEALA', 'Lichid negru de scris'], ['PAGINA', 'O foaie din carte']],
        ['Prima carte tipărită cu litere mobile a apărut acum peste 550 de ani.', 'Literele de tipar erau așezate în oglindă, ca să apară corect pe hârtie.', 'O tipografie modernă poate tipări zeci de mii de ziare într-o oră.']),
      r('moara', 'Moara de Vânt', 'Aripi, grâu și făină', '🌾', 300,
        'Vântul s-a oprit și ușa morii s-a înțepenit. Morarul a lăsat <b>{n} probe</b> — rezolvă-le și aripile pornesc din nou.',
        ['math', 'weights', 'count', 'sequence', 'dial', 'sliders', 'money', 'riddle', 'logic'],
        sc('planks', ['#d6b370', '#b8955a', '#8b6a3a'], 'planks', ['#a16207', '#713f12'], 'windows', 'wood', '#dc2626', '#38bdf8', '#a16207', '#78716c',
           [['roata', 'Roata morii'], ['carucior', 'Căruciorul cu grâu'], ['cadran', 'Cântarul'], ['butoi', 'Butoiul cu făină']]),
        [['GRAU', 'Din el se face făina'], ['VANT', 'Învârte aripile morii'], ['SAC', 'Se umple cu făină'], ['MOARA', 'Macină grâul'], ['PIATRA', 'Zdrobește boabele'], ['MORAR', 'Lucrează la moară']],
        ['Aripile morii se rotesc mereu în același sens, cu vântul.', 'Din 100 kg de grâu ies cam 75 kg de făină albă.', 'Morile de vânt vechi puteau fi rotite cu totul, ca aripile să prindă vântul.']),
      r('tamplarie', 'Atelierul Tâmplarului', 'Rumeguș și lemn parfumat', '🪚', 300,
        'Tâmplarul a plecat după scânduri și a proptit ușa cu un dulap. Rezolvă <b>{n} probe</b> ca să afli cum îl miști.',
        ['shapes', 'math', 'count', 'weights', 'sequence', 'order', 'logic', 'sliders', 'match'],
        sc('planks', ['#b45309', '#92400e', '#78350f'], 'planks', ['#a16207', '#713f12'], 'lamp', 'wood', '#0ea5e9', '#f59e0b', '#c2762a', '#94a3b8',
           [['unelte', 'Panoul cu unelte'], ['masa', 'Bancul de lucru'], ['cutii', 'Lăzile cu scânduri'], ['tron', 'Scaunul sculptat']]),
        [['LEMN', 'Din el se fac mesele'], ['CUI', 'Îl bați cu ciocanul'], ['SCAUN', 'Stai pe el'], ['RIGLA', 'Măsoară lungimea'], ['RUMEGUS', 'Praf de lemn'], ['FIERASTRAU', 'Taie scândura']],
        ['Lemnul de brad miroase frumos pentru că are rășină.', 'Inelele din trunchiul unui copac tăiat îți spun câți ani a trăit.', 'Un tâmplar măsoară de două ori înainte să taie o dată.']),
      r('frizerie', 'Frizeria', 'Foarfeci, oglinzi și spumă', '💈', 300,
        'Frizerul a ieșit un minut și ușa s-a încuiat de la sine. Oglinzile îți arată <b>{n} probe</b> — rezolvă-le și ieși tuns frumos.',
        ['count', 'math', 'clock', 'money', 'shapes', 'order', 'riddle', 'match', 'sequence'],
        sc('tiles', ['#e0f2fe', '#bae6fd', '#93c5fd'], 'checker', ['#e5e7eb', '#9ca3af'], 'lamp', 'glass', '#dc2626', '#2563eb', '#7c4a1e', '#94a3b8',
           [['oglinda', 'Oglinda'], ['tron', 'Scaunul frizerului'], ['raft', 'Raftul cu sticluțe'], ['ceas', 'Ceasul']]),
        [['PAR', 'Crește pe cap'], ['PIEPTENE', 'Are dinți, dar nu mușcă'], ['FOARFECA', 'Taie părul'], ['SPUMA', 'Albă, pentru bărbierit'], ['OGLINDA', 'Te vezi în ea'], ['TUNSOARE', 'Cum ți-a aranjat frizerul părul']],
        ['Părul crește cam un centimetr pe lună.', 'Stâlpul cu dungi roșii și albe de la frizerie e un semn vechi de sute de ani.', 'Un om are pe cap în jur de 100.000 de fire de păr.']),
      r('cofetarie', 'Cofetăria', 'Frișcă, ciocolată și glazură', '🧁', 300,
        'Cofetarul a intrat în cămară după zahăr și ușa s-a blocat cu tine în laborator. <b>Termină cele {n} rețete</b> și ieși cu un ecler.',
        ['math', 'money', 'count', 'weights', 'shapes', 'sequence', 'match', 'sliders', 'order'],
        sc('dots', ['#fce7f3', '#fbcfe8', '#f9a8d4'], 'checker', ['#fde68a', '#f59e0b'], 'bulbs', 'glass', '#ec4899', '#a855f7', '#92400e', '#94a3b8',
           [['tort', 'Tortul'], ['vitrina', 'Vitrina cu prăjituri'], ['ceainic', 'Ceainicul'], ['cadran', 'Cântarul']]),
        [['TORT', 'Are lumânări de ziua ta'], ['ZAHAR', 'Face totul dulce'], ['FRISCA', 'Albă și pufoasă'], ['ECLER', 'Prăjitură cu cremă'], ['GLAZURA', 'Îmbracă prăjitura'], ['CIOCOLATA', 'Maro și dulce']],
        ['Ciocolata se topește la temperatura corpului, de aceea se înmoaie în mână.', 'Frișca se face batând smântâna până prinde aer.', 'Zahărul brun e mai închis pentru că păstrează puțină melasă.']),
      r('florarie', 'Florăria', 'Petale, ghivece și parfum', '💐', 300,
        'Florăreasa a plecat cu buchetul de nuntă și a uitat ușa încuiată. Ghivecele ascund <b>{n} probe</b> — rezolvă-le și ieși cu un trandafir.',
        ['count', 'math', 'shapes', 'sequence', 'match', 'money', 'riddle', 'logic', 'order'],
        sc('plain', ['#bbf7d0', '#86efac', '#4ade80'], 'tiles', ['#a8a29e', '#57534e'], 'windows', 'glass', '#ec4899', '#f59e0b', '#92400e', '#94a3b8',
           [['cos_flori', 'Coșul cu flori'], ['vaza', 'Vaza cea mare'], ['planta', 'Ferigă'], ['cactus', 'Cactusul']]),
        [['LALEA', 'Floare de primăvară'], ['PETALA', 'O parte din floare'], ['GHIVECI', 'Casa plantei'], ['BUCHET', 'Mai multe flori legate'], ['TRANDAFIR', 'Floare cu spini'], ['SEMINTE', 'Din ele cresc plantele']],
        ['Floarea-soarelui își întoarce capul după soare în fiecare zi.', 'Un trandafir tăiat ține mai mult în vază dacă tai tulpina oblic.', 'Unele plante își închid florile noaptea și le deschid dimineața.'])
    ] },

    /* ================================================================
       LUMEA 5 — CĂLĂTORIE ÎN JURUL LUMII
       ================================================================ */
    { id: 'lume', name: 'În Jurul Lumii', emoji: '🌍', desc: 'Japonia, Maroc, Veneția, Londra și mai departe', rooms: [
      r('japonia', 'Casa de Ceai din Japonia', 'Ușă de hârtie și bonsai', '🏯', 320,
        'Ceremonia ceaiului s-a terminat, dar ușa glisantă de hârtie e blocată. Rezolvă <b>{n} probe</b> în liniște, ca un adevărat samurai.',
        ['math', 'shapes', 'sequence', 'count', 'logic', 'order', 'cipher', 'match', 'riddle'],
        sc('panels', ['#fef3c7', '#fde68a', '#d6b370'], 'planks', ['#a16207', '#713f12'], 'lamp', 'shoji', '#dc2626', '#0ea5e9', '#7c2d12', '#94a3b8',
           [['ceainic', 'Ceainicul'], ['masca', 'Masca de teatru'], ['planta', 'Bonsaiul'], ['tablou', 'Tabloul cu Muntele Fuji']]),
        [['CEAI', 'Băutură caldă din frunze'], ['OREZ', 'Boabe albe, mâncate cu bețișoare'], ['BONSAI', 'Copac pitic în ghiveci'], ['KIMONO', 'Haină japoneză'], ['SUSHI', 'Orez cu pește'], ['DRAGON', 'Balaur din povești']],
        ['În Japonia oamenii se descalță înainte să intre în casă.', 'Bonsaiul e un copac adevărat ținut mic prin tăierea rădăcinilor și ramurilor.', 'Trenurile japoneze sunt atât de punctuale încât o întârziere de un minut e o știre.']),
      r('maroc', 'Bazarul din Maroc', 'Covoare, lămpi și mirodenii', '🕌', 320,
        'Negustorul a tras perdeaua grea și a plecat la rugăciune. Printre covoare și lămpi sunt <b>{n} probe</b> — ele îți deschid drumul.',
        ['money', 'math', 'count', 'shapes', 'match', 'order', 'sequence', 'weights', 'logic'],
        sc('dots', ['#c2410c', '#9a3412', '#7c2d12'], 'carpet', ['#7f1d1d', '#450a0a'], 'candles', 'curtain', '#dc2626', '#fbbf24', '#92400e', '#b45309',
           [['vaza', 'Urciorul'], ['raft', 'Raftul cu mirodenii'], ['cufar', 'Cufărul negustorului'], ['ceainic', 'Ceainicul de aramă']]),
        [['COVOR', 'Se întinde pe podea'], ['LAMPA', 'Dă lumină'], ['PIATA', 'Loc unde cumperi lucruri'], ['MENTA', 'Plantă pentru ceai'], ['SCORTISOARA', 'Mirodenie maro, dulce'], ['CAMILA', 'Animal cu cocoașe']],
        ['În bazarurile din Maroc prețul se negociază: e normal să ceri mai ieftin.', 'Ceaiul cu mentă se toarnă de sus, ca să facă spumă.', 'Covoarele marocane sunt înnodate manual, nod cu nod, luni întregi.']),
      r('venetia', 'Podul din Veneția', 'Gondole, măști și canale', '🛶', 320,
        'Gondolierul a plecat cu vâsla, iar poarta de pe pod e încuiată. <b>Rezolvă probele</b> ascunse printre măști ca să chemi altă gondolă.',
        ['count', 'math', 'shapes', 'riddle', 'order', 'sequence', 'logic', 'match', 'money'],
        sc('bricks', ['#f9a8d4', '#f472b6', '#be185d'], 'water', ['#0e7490', '#164e63'], 'moon', 'gate', '#7c3aed', '#fbbf24', '#7c4a1e', '#9ca3af',
           [['ancora', 'Ancora gondolei'], ['masca', 'Masca de carnaval'], ['portret', 'Portretul dogelui'], ['steag', 'Steagul cu leu']], 'night'),
        [['GONDOLA', 'Barcă lungă și neagră'], ['POD', 'Trece peste apă'], ['MASCA', 'O pui pe față'], ['CANAL', 'Stradă de apă'], ['VASLA', 'Împinge barca'], ['CARNAVAL', 'Sărbătoare cu costume']],
        ['Veneția are peste 400 de poduri și nicio mașină.', 'Casele din Veneția stau pe stâlpi de lemn înfipți în noroi de sute de ani.', 'Gondolele sunt vopsite toate în negru, după o regulă veche.']),
      r('londra', 'Turnul cu Ceas din Londra', 'Ploaie, autobuze roșii și ceai', '🎡', 320,
        'Ai urcat în turn ca să vezi ceasul uriaș și paznicul a încuiat scara. <b>Găsește codul</b> în cele {n} colțuri ale camerei.',
        ['clock', 'math', 'count', 'money', 'sequence', 'culture', 'logic', 'order', 'riddle'],
        sc('stone', ['#9ca3af', '#6b7280', '#4b5563'], 'tiles', ['#a3a3a3', '#525252'], 'windows', 'wood', '#dc2626', '#2563eb', '#7c4a1e', '#9ca3af',
           [['ceas', 'Ceasul uriaș'], ['cutie_postala', 'Cutia poștală roșie'], ['valiza', 'Valiza călătorului'], ['portret', 'Portretul reginei']], 'sunset'),
        [['CEAS', 'Arată ora'], ['PLOAIE', 'Cade des în Londra'], ['UMBRELA', 'Te apără de ploaie'], ['AUTOBUZ', 'Roșu, cu etaj'], ['TURN', 'Clădire înaltă'], ['PALAT', 'Locuiește regele în el']],
        ['Ceasul Big Ben bate atât de tare încât se aude de la kilometri distanță.', 'Autobuzele roșii cu etaj din Londra au apărut acum peste 100 de ani.', 'La Londra se circulă pe partea stângă a drumului.']),
      r('india', 'Palatul din India', 'Elefanți, mătase și culori', '🐘', 320,
        'Maharajahul a plecat la vânătoare și paznicii au tras perdelele grele. Cele <b>{n} comori</b> din sală îți spun codul.',
        ['math', 'count', 'shapes', 'sequence', 'match', 'order', 'logic', 'weights', 'riddle'],
        sc('dots', ['#f97316', '#ea580c', '#c2410c'], 'carpet', ['#7c3aed', '#4c1d95'], 'candles', 'curtain', '#facc15', '#ec4899', '#92400e', '#fbbf24',
           [['vaza', 'Vaza aurită'], ['tron', 'Tronul maharajahului'], ['steag', 'Steagul cu elefant'], ['masca', 'Masca de dans']]),
        [['ELEFANT', 'Are trompă'], ['TIGRU', 'Felină cu dungi'], ['OREZ', 'Boabe albe'], ['MATASE', 'Material fin și lucios'], ['PALAT', 'Casa regelui'], ['CURRY', 'Mâncare cu multe mirodenii']],
        ['Elefanții își folosesc trompa ca pe o mână: pot ridica un bob de mazăre.', 'În India se vorbesc peste 20 de limbi oficiale.', 'Taj Mahal, cel mai vestit palat din India, e făcut din marmură albă.']),
      r('vest', 'Saloonul din Vest', 'Cizme, pălării și un pian', '🤠', 320,
        'Șeriful a plecat după bandiți și a lăsat ușile batante blocate. <b>Rezolvă probele</b> de la bar ca să pleci cu diligența.',
        ['math', 'money', 'count', 'sequence', 'order', 'riddle', 'logic', 'dial', 'weights'],
        sc('planks', ['#b45309', '#92400e', '#78350f'], 'planks', ['#a16207', '#713f12'], 'lamp', 'saloon', '#dc2626', '#fbbf24', '#a16207', '#94a3b8',
           [['butoi', 'Butoiul'], ['pian', 'Pianul'], ['afis', 'Afișul „Se caută”'], ['cutii', 'Lăzile']]),
        [['CAL', 'Îl călărește cowboy-ul'], ['PALARIE', 'O poartă pe cap'], ['CIZMA', 'Încălțăminte cu pinteni'], ['SERIF', 'Are stea pe piept'], ['CACTUS', 'Plantă cu țepi'], ['DILIGENTA', 'Trăsură cu cai']],
        ['Ușile batante ale saloonului se deschid în ambele sensuri, ca să intri repede.', 'Pălăria cowboy-ului are boruri mari ca să-l apere de soare și ploaie.', 'Un cal poate dormi și în picioare.']),
      r('africa', 'Satul din Savană', 'Tobe, măști și un foc mare', '🦁', 320,
        'Dansul din jurul focului s-a terminat, iar poarta satului e legată cu liane. Cele <b>{n} probe</b> ale bătrânilor îți arată nodul.',
        ['count', 'riddle', 'match', 'math', 'sequence', 'shapes', 'logic', 'order', 'culture'],
        sc('plain', ['#fbbf24', '#f59e0b', '#b45309'], 'sand', ['#d6b370', '#a16207'], 'sun', 'vine', '#dc2626', '#16a34a', '#92400e', '#78716c',
           [['toba', 'Toba'], ['masca', 'Masca din lemn'], ['cort', 'Coliba'], ['foc', 'Focul din mijlocul satului']]),
        [['LEU', 'Regele animalelor'], ['ZEBRA', 'Cal cu dungi'], ['GIRAFA', 'Are gâtul lung'], ['TOBA', 'Bați în ea'], ['SAVANA', 'Câmpie cu iarbă înaltă'], ['BAOBAB', 'Copac cu trunchi uriaș']],
        ['Girafa are aceeași număr de oase în gât ca omul, doar că mult mai lungi.', 'Baobabul poate ține în trunchi apă cât o piscină mică.', 'Tobele erau folosite ca să trimită mesaje de la un sat la altul.']),
      r('alpi', 'Cabana din Alpi', 'Zăpadă, vaci cu clopoței și cacao', '🏔️', 320,
        'Telecabina s-a oprit din cauza ninsorii și ești blocat în cabană. <b>Rezolvă probele</b> ca să repornești motorul telecabinei.',
        ['math', 'count', 'clock', 'sequence', 'weights', 'sliders', 'logic', 'riddle', 'shapes'],
        sc('planks', ['#d6b370', '#b8955a', '#8b6a3a'], 'planks', ['#a16207', '#713f12'], 'windows', 'wood', '#dc2626', '#38bdf8', '#a16207', '#9ca3af',
           [['sanie', 'Sania'], ['clopot', 'Clopotul vacilor'], ['soba', 'Soba cu lemne'], ['coarne', 'Coarnele de cerb']], 'snow'),
        [['SCHI', 'Aluneci cu ele pe zăpadă'], ['GHEATA', 'Apă înghețată'], ['CACAO', 'Băutură caldă, maro'], ['CABANA', 'Casă de lemn la munte'], ['ZAPADA', 'Fulgi albi'], ['TELECABINA', 'Te urcă pe munte prin aer']],
        ['Vacile din Alpi poartă clopoței ca să fie găsite ușor pe pajiști.', 'Zăpada reflectă lumina soarelui, de aceea te bronzezi și iarna la munte.', 'Cel mai înalt vârf din Alpi, Mont Blanc, are aproape 5 kilometri.']),
      r('china', 'Pagoda Chinezească', 'Lampioane roșii și dragoni', '🏮', 320,
        'Festivalul lampioanelor s-a încheiat și pagoda s-a închis. Dragonul de hârtie păzește <b>{n} probe</b> — rezolvă-le și ieși.',
        ['math', 'sequence', 'count', 'shapes', 'cipher', 'order', 'logic', 'match', 'riddle'],
        sc('panels', ['#dc2626', '#b91c1c', '#7f1d1d'], 'tiles', ['#a8a29e', '#57534e'], 'lamp', 'wood', '#facc15', '#dc2626', '#7c2d12', '#fbbf24',
           [['vaza', 'Vaza de porțelan'], ['steag', 'Steagul cu dragon'], ['ceainic', 'Ceainicul'], ['tablou', 'Tabloul cu bambus']]),
        [['DRAGON', 'Balaur din legende'], ['PANDA', 'Urs alb cu negru'], ['BAMBUS', 'Plantă înaltă, mâncată de panda'], ['ZID', 'Cel mai lung din lume'], ['LAMPION', 'Lampă de hârtie'], ['PORTELAN', 'Ceramică fină, albă']],
        ['Marele Zid Chinezesc e atât de lung încât ar ajunge de la București la Lisabona și înapoi.', 'Hârtia, busola și artificiile au fost inventate în China.', 'Panda mănâncă bambus aproape toată ziua — până la 14 ore.']),
      r('mexic', 'Piața din Mexic', 'Chitare, ardei și piñata', '🌮', 320,
        'Fiesta s-a terminat și porțile pieței s-au închis. Piñata a împrăștiat <b>{n} probe</b> — rezolvă-le și ieși dansând.',
        ['math', 'money', 'count', 'shapes', 'sequence', 'match', 'order', 'logic', 'riddle'],
        sc('plain', ['#f97316', '#ea580c', '#c2410c'], 'tiles', ['#d6b370', '#8b6a3a'], 'bulbs', 'wood', '#22c55e', '#ec4899', '#a16207', '#94a3b8',
           [['cactus', 'Cactusul'], ['chitara', 'Chitara'], ['masca', 'Masca colorată'], ['lada_fructe', 'Lada cu ardei']]),
        [['TACO', 'Lipie umplută'], ['ARDEI', 'Uneori iute'], ['CHITARA', 'Instrument cu corzi'], ['CACTUS', 'Plantă cu țepi'], ['SOMBRERO', 'Pălărie cu boruri mari'], ['PINATA', 'O spargi și cad bomboane']],
        ['Ciocolata a fost băută prima dată în Mexic, amară și cu ardei iute.', 'Piñata se sparge legat la ochi, iar bomboanele cad din ea.', 'Roșiile, porumbul și avocado vin toate din Mexic.'])
    ] },

    /* ================================================================
       LUMEA 6 — TĂRÂMUL POVEȘTILOR
       ================================================================ */
    { id: 'povesti', name: 'Tărâmul Poveștilor', emoji: '🧚', desc: 'Vrăjitoare, balauri, prințese și pitici', rooms: [
      r('vrajitoare', 'Casa Vrăjitoarei', 'Cazan, broaște și pânze de păianjen', '🧹', 320,
        'Vrăjitoarea a plecat cu mătura, iar ușa s-a încuiat cu o vrajă. Cele <b>{n} probe</b> din casă sunt cuvintele care o desfac.',
        ['riddle', 'anagram', 'cipher', 'count', 'math', 'logic', 'sequence', 'weights', 'match'],
        sc('planks', ['#6d28d9', '#4c1d95', '#2e1065'], 'planks', ['#3b0764', '#1e0a3c'], 'candles', 'wood', '#22c55e', '#f97316', '#4c1d95', '#78716c',
           [['cazan', 'Cazanul'], ['borcan', 'Borcanul cu ochi de broască'], ['panza', 'Pânza de păianjen'], ['colivie', 'Colivia cu corb']]),
        [['MATURA', 'Zboară cu ea'], ['VRAJA', 'Cuvinte magice'], ['CAZAN', 'Fierbe poțiunea'], ['BROASCA', 'Verde și orăcăie'], ['PISICA', 'Neagră, pe pervaz'], ['POTIUNE', 'Băutură fermecată']],
        ['În povești, vrăjitoarele au pisici negre pentru că acestea se ascund bine noaptea.', 'Cuvântul „abracadabra” e vechi de aproape 2000 de ani.', 'Cazanul vrăjitoarei e, de fapt, o oală mare de fier ca cele din bucătăriile vechi.']),
      r('printesa', 'Turnul Prințesei', 'Oglinzi, coroane și un balcon', '👑', 300,
        'Prințesa a coborât pe frânghia de cearșafuri și a lăsat ușa turnului încuiată. <b>Rezolvă probele</b> ca să cobori și tu.',
        ['math', 'riddle', 'count', 'shapes', 'match', 'order', 'sequence', 'logic', 'proverb'],
        sc('stone', ['#fbcfe8', '#f9a8d4', '#f472b6'], 'carpet', ['#be185d', '#831843'], 'windows', 'wood', '#7c3aed', '#fbbf24', '#a16207', '#fbbf24',
           [['oglinda', 'Oglinda fermecată'], ['tron', 'Tronul'], ['steag', 'Steagul regatului'], ['harta', 'Harta regatului']]),
        [['COROANA', 'O poartă regina pe cap'], ['TURN', 'Înalt, cu o singură fereastră'], ['BAL', 'Petrecere cu dans'], ['ROCHIE', 'Haină de bal'], ['CASTEL', 'Locuiește regele în el'], ['PANTOF', 'Cenușăreasa l-a pierdut']],
        ['Cel mai înalt castel din povești ar avea nevoie de peste 300 de trepte.', 'Coroanele regilor adevărați erau atât de grele încât se purtau doar la ceremonii.', 'Turnurile aveau scări în spirală ca să fie apărate mai ușor.']),
      r('balaur', 'Bârlogul Balaurului', 'Aur, oase și fum', '🐉', 340,
        'Balaurul doarme pe grămada de aur, iar stânca de la intrare e trasă. Rezolvă <b>{n} probe</b> în șoaptă, fără să-l trezești!',
        ['math', 'count', 'money', 'riddle', 'logic', 'sequence', 'weights', 'cipher', 'shapes'],
        sc('cave', ['#7f1d1d', '#450a0a', '#1c1917'], 'stone', ['#44403c', '#1c1917'], 'torches', 'cave', '#fbbf24', '#ef4444', '#57534e', '#78716c',
           [['cufar', 'Cufărul cu aur'], ['ou', 'Oul de balaur'], ['scut', 'Scutul cavalerului'], ['foc', 'Focul balaurului']]),
        [['AUR', 'Metal galben, prețios'], ['FOC', 'Îl scuipă balaurul'], ['ARIPA', 'Balaurul zboară cu ea'], ['SOLZ', 'Acoperă pielea balaurului'], ['COMOARA', 'Grămadă de aur'], ['CAVALER', 'Luptă cu balaurul']],
        ['Poveștile cu balauri există în aproape toate țările lumii.', 'Cei mai mari „balauri” adevărați sunt varanii de Komodo, șopârle de 3 metri.', 'Aurul nu ruginește niciodată, de aceea comorile vechi strălucesc și azi.']),
      r('pitici', 'Coliba Piticilor', 'Șapte scaune, șapte căni', '🍄', 300,
        'Piticii au plecat la mină și au încuiat coliba. Albă-ca-Zăpada a lăsat <b>{n} probe</b> pe masă — rezolvă-le și ieși.',
        ['count', 'math', 'sequence', 'order', 'match', 'riddle', 'shapes', 'logic', 'weights'],
        sc('planks', ['#b45309', '#92400e', '#78350f'], 'planks', ['#a16207', '#713f12'], 'lamp', 'wood', '#dc2626', '#22c55e', '#a16207', '#94a3b8',
           [['masa', 'Masa cu șapte scaune'], ['dulap', 'Dulapul cu haine mici'], ['ceainic', 'Ceainicul'], ['cristal', 'Diamantele din mină']]),
        [['PITIC', 'Om mic cu barbă'], ['MINA', 'Piticii sapă în ea'], ['MAR', 'Fruct otrăvit în poveste'], ['BARBA', 'Piticii o au lungă'], ['DIAMANT', 'Piatră strălucitoare'], ['TARNACOP', 'Unealta minerului']],
        ['În povestea originală, cei șapte pitici nu aveau nume — le-au primit abia în desenul animat.', 'Diamantele sunt cele mai tari pietre de pe Pământ: pot zgâria orice.', 'Minerii de demult luau cu ei canari — dacă pasărea amețea, aerul era periculos.']),
      r('zapada', 'Palatul de Zăpadă', 'Gheață, cristale și o regină', '❄️', 320,
        'Regina zăpezii a înghețat ușa palatului. Doar cine rezolvă cele <b>{n} probe de gheață</b> o poate topi.',
        ['math', 'shapes', 'count', 'sequence', 'logic', 'cipher', 'order', 'match', 'riddle'],
        sc('ice', ['#bae6fd', '#7dd3fc', '#38bdf8'], 'ice', ['#e0f2fe', '#7dd3fc'], 'moon', 'ice', '#7c3aed', '#f0abfc', '#0369a1', '#94a3b8',
           [['tron', 'Tronul de gheață'], ['cristal', 'Cristalele'], ['sanie', 'Sania'], ['oglinda', 'Oglinda înghețată']], 'night'),
        [['FULG', 'Cade din cer iarna'], ['GHEATA', 'Apă înghețată'], ['REGINA', 'Stăpâna palatului'], ['SANIE', 'Alunecă pe zăpadă'], ['CRISTAL', 'Strălucește și e transparent'], ['VISCOL', 'Vânt cu zăpadă']],
        ['Fiecare fulg de zăpadă are șase brațe și nu există doi la fel.', 'Gheața plutește pe apă pentru că e mai ușoară decât apa lichidă.', 'În unele orașe se construiesc iarna hoteluri întregi din gheață.']),
      r('spiridusi', 'Atelierul Spiridușilor', 'Cadouri, clopoței și liste', '🎁', 300,
        'Spiridușii au plecat să încarce sania și au încuiat atelierul. <b>Împachetează cele {n} probe</b> ca să ajungi la ei.',
        ['count', 'math', 'sequence', 'order', 'shapes', 'match', 'money', 'logic', 'weights'],
        sc('dots', ['#dc2626', '#b91c1c', '#7f1d1d'], 'planks', ['#a16207', '#713f12'], 'bulbs', 'wood', '#22c55e', '#facc15', '#92400e', '#94a3b8',
           [['cutii', 'Cadourile'], ['sanie', 'Sania'], ['clopot', 'Clopotul'], ['masa', 'Masa cu jucării']]),
        [['CADOU', 'Îl primești de sărbători'], ['SANIE', 'Trasă de reni'], ['REN', 'Animal cu coarne mari'], ['BRAD', 'Îl împodobim'], ['GLOB', 'Ornament rotund pentru brad'], ['FUNDA', 'Se leagă pe cadou']],
        ['Renii pot vedea lumina ultravioletă, de aceea găsesc hrana și în zăpadă.', 'Tradiția bradului împodobit a început în Germania acum câteva sute de ani.', 'Cel mai lung șir de luminițe de sărbători a avut peste 100 de kilometri.']),
      r('padure_fermecata', 'Pădurea Fermecată', 'Licurici, zâne și o fântână', '✨', 320,
        'Zânele te-au adus în poiana lor, dar ieșirea e ascunsă de o vrajă. Cele <b>{n} probe</b> ale poienii îți arată cărarea.',
        ['riddle', 'count', 'math', 'sequence', 'anagram', 'match', 'logic', 'shapes', 'proverb'],
        sc('leaves', ['#14532d', '#166534', '#052e16'], 'grass', ['#15803d', '#14532d'], 'moon', 'vine', '#f0abfc', '#facc15', '#7c4a1e', '#78716c',
           [['ou', 'Oul auriu'], ['cristal', 'Cristalul luminos'], ['borcan', 'Borcanul cu licurici'], ['fantana', 'Fântâna dorințelor']], 'night'),
        [['ZANA', 'Are aripi și baghetă'], ['MAGIE', 'Face lucruri imposibile'], ['POIANA', 'Loc deschis în pădure'], ['BAGHETA', 'Zâna face vrăji cu ea'], ['LICURICI', 'Insectă care luminează'], ['CIUPERCA', 'Are pălărie']],
        ['Licuricii produc lumină fără căldură — un bec ar arde, dar ei nu.', 'Unele ciuperci din pădure strălucesc verde noaptea.', 'În poveștile vechi, cercurile de ciuperci erau numite „cercuri de zâne”.']),
      r('zmeu', 'Moara Zmeului', 'Roți uriașe și buzdugan', '🌪️', 340,
        'Zmeul a plecat la vânătoare și a încuiat moara cu tine înăuntru. <b>Rezolvă probele</b> ca să-i găsești cheia ascunsă.',
        ['math', 'weights', 'count', 'sequence', 'riddle', 'logic', 'dial', 'sliders', 'cipher'],
        sc('stone', ['#4b5563', '#374151', '#1f2937'], 'stone', ['#374151', '#111827'], 'torches', 'gate', '#dc2626', '#f97316', '#57534e', '#78716c',
           [['roata', 'Roata morii'], ['cazan', 'Cazanul zmeului'], ['nicovala', 'Nicovala'], ['cufar', 'Cufărul cu buzdugane']]),
        [['ZMEU', 'Personaj rău din basme'], ['BUZDUGAN', 'Arma zmeului'], ['MOARA', 'Macină grâul'], ['CAL', 'Năzdrăvan, în basme'], ['PALOS', 'Sabie mare'], ['ILEANA', 'Cosânzeana din povești']],
        ['În basmele românești, calul năzdrăvan mănâncă jar ca să prindă puteri.', 'Buzduganul zmeului era aruncat înainte ca să anunțe că se întoarce acasă.', 'Făt-Frumos crește în basme „într-un an cât alții în zece”.']),
      r('alibaba', 'Peștera lui Ali Baba', 'Sesam, deschide-te!', '💎', 320,
        'Ai spus „Sesam, deschide-te!”, dar ai uitat cuvintele de închidere. Comorile ascund <b>{n} probe</b> — ele îți arată ieșirea.',
        ['money', 'math', 'count', 'cipher', 'anagram', 'logic', 'sequence', 'order', 'weights'],
        sc('cave', ['#b45309', '#92400e', '#451a03'], 'sand', ['#fde68a', '#d6b370'], 'candles', 'stone', '#fbbf24', '#a855f7', '#92400e', '#fbbf24',
           [['vaza', 'Urciorul'], ['cufar', 'Cufărul cu monede'], ['cristal', 'Pietrele prețioase'], ['ceainic', 'Lampa fermecată']]),
        [['SESAM', 'Cuvântul magic'], ['COMOARA', 'Aur și pietre prețioase'], ['HOT', 'Fură lucruri'], ['LAMPA', 'Freac-o și iese duhul'], ['PESTERA', 'Gaură mare în stâncă'], ['MONEDA', 'Ban rotund']],
        ['Susanul („sesamul”) e o sămânță mică din care se face ulei — de aici cuvântul magic.', 'Poveștile cu Ali Baba fac parte din „1001 de nopți”, spuse de Șeherezada.', 'Cea mai mare monedă de aur din lume cântărește cât un om.']),
      r('corabie_zburatoare', 'Corabia Zburătoare', 'Pânze printre nori', '⛵', 340,
        'Corabia plutește printre nori, iar cabina căpitanului e încuiată. <b>Rezolvă probele</b> ca să prinzi timona înainte de furtună.',
        ['math', 'sequence', 'count', 'clock', 'cipher', 'logic', 'shapes', 'dial', 'riddle'],
        sc('night', ['#1e1b4b', '#312e81', '#4c1d95'], 'planks', ['#7c4a1e', '#3f2107'], 'moon', 'wood', '#fbbf24', '#38bdf8', '#a16207', '#94a3b8',
           [['roata', 'Timona'], ['ancora', 'Ancora'], ['harta', 'Harta cerului'], ['telescop', 'Luneta']], 'night'),
        [['NOR', 'Alb și pufos pe cer'], ['VANT', 'Umflă pânzele'], ['STEA', 'Strălucește noaptea'], ['PANZA', 'Prinde vântul'], ['TIMONA', 'Cârma corabiei'], ['CAPITAN', 'Conduce corabia']],
        ['Marinarii de demult se orientau noaptea după Steaua Polară, care arată mereu nordul.', 'Norii par ușori, dar un nor mare cântărește cât sute de elefanți.', 'Cel mai rapid vânt măsurat vreodată a bătut cu peste 400 km/h.'])
    ] },

    /* ================================================================
       LUMEA 7 — ȘTIINȚĂ ȘI TEHNOLOGIE
       ================================================================ */
    { id: 'stiinta', name: 'Știință și Tehnologie', emoji: '🔬', desc: 'Observatoare, fabrici, servere și mine', rooms: [
      r('observator', 'Observatorul Astronomic', 'Telescop și cer înstelat', '🔭', 340,
        'Cupola s-a închis peste telescop cu tine înăuntru. <b>Aliniază cele {n} instrumente</b> ca să se deschidă din nou.',
        ['math', 'sequence', 'count', 'culture', 'shapes', 'logic', 'dial', 'clock', 'cipher'],
        sc('night', ['#0f172a', '#1e1b4b', '#312e81'], 'metal', ['#334155', '#0f172a'], 'moon', 'metal', '#38bdf8', '#fbbf24', '#7c4a1e', '#94a3b8',
           [['telescop', 'Telescopul'], ['harta', 'Harta stelelor'], ['ecran', 'Monitorul'], ['glob', 'Globul ceresc']], 'night'),
        [['STEA', 'Punct luminos pe cer'], ['LUNA', 'Se vede noaptea'], ['MARTE', 'Planeta roșie'], ['COMETA', 'Are coadă'], ['TELESCOP', 'Apropie stelele'], ['PLANETA', 'Se rotește în jurul Soarelui']],
        ['Lumina unor stele pe care le vezi a plecat spre noi înainte să te naști tu.', 'Luna se îndepărtează de Pământ cu câțiva centimetri în fiecare an.', 'Pe Marte, o zi durează aproape la fel ca pe Pământ: 24 de ore și 40 de minute.']),
      r('centrala', 'Centrala Electrică', 'Cabluri, contoare și scântei', '⚡', 340,
        'Un fulger a lovit centrala și ușile s-au blocat. <b>Pune contoarele la loc</b> în cele {n} probe și curentul revine.',
        ['math', 'sequence', 'sliders', 'dial', 'count', 'logic', 'order', 'shapes', 'weights'],
        sc('metal', ['#78716c', '#57534e', '#44403c'], 'metal', ['#6b7280', '#374151'], 'neon', 'metal', '#facc15', '#22d3ee', '#7c4a1e', '#9ca3af',
           [['panou', 'Panoul de comandă'], ['cadran', 'Contorul'], ['unelte', 'Uneltele electricianului'], ['seif', 'Cutia de siguranțe']]),
        [['CURENT', 'Trece prin fire'], ['BEC', 'Luminează camera'], ['FIR', 'Prin el trece curentul'], ['PRIZA', 'Bagi ștecherul în ea'], ['BATERIE', 'Dă energie jucăriilor'], ['FULGER', 'Lumină din nor']],
        ['Curentul electric merge prin fire aproape cu viteza luminii.', 'Nu atinge niciodată prizele cu mâinile ude: apa conduce curentul.', 'Un fulger are destulă energie ca să aprindă un bec timp de luni întregi.']),
      r('meteo', 'Stația Meteo', 'Vânt, nori și baloane', '🌦️', 320,
        'Furtuna a blocat ușa stației. <b>Citește aparatele</b> în cele {n} probe și vei ști când poți ieși.',
        ['math', 'count', 'sequence', 'dial', 'clock', 'logic', 'culture', 'shapes', 'match'],
        sc('tiles', ['#bae6fd', '#7dd3fc', '#38bdf8'], 'plain', ['#94a3b8', '#475569'], 'windows', 'glass', '#f59e0b', '#0ea5e9', '#7c4a1e', '#94a3b8',
           [['cadran', 'Barometrul'], ['ecran', 'Harta cu nori'], ['glob', 'Globul'], ['baloane', 'Balonul meteo']], 'sunset'),
        [['NOR', 'Aduce ploaia'], ['VANT', 'Îl simți, dar nu-l vezi'], ['PLOAIE', 'Picături din cer'], ['FULGER', 'Lumină în furtună'], ['CURCUBEU', 'Apare după ploaie'], ['GRINDINA', 'Bucăți de gheață din cer']],
        ['Tunetul se aude după fulger pentru că sunetul e mai lent decât lumina.', 'Numără secundele dintre fulger și tunet: la fiecare 3 secunde, furtuna e la un kilometru.', 'Baloanele meteo urcă la 30 de kilometri, mai sus decât avioanele.']),
      r('servere', 'Sala Serverelor', 'Cabluri, ventilatoare și leduri', '💻', 340,
        'Ușa sălii se deschide doar cu parola, iar parola s-a pierdut. <b>Descifrează cele {n} probe</b> ale calculatoarelor.',
        ['cipher', 'sequence', 'math', 'logic', 'count', 'order', 'shapes', 'anagram', 'sliders'],
        sc('metal', ['#1f2937', '#111827', '#030712'], 'checker', ['#374151', '#111827'], 'neon', 'elevator', '#22c55e', '#22d3ee', '#7c4a1e', '#4b5563',
           [['ecran', 'Monitorul'], ['panou', 'Serverul'], ['birou', 'Biroul programatorului'], ['robot', 'Robotul de serviciu']]),
        [['COD', 'Îl scrie programatorul'], ['MOUSE', 'Îl miști pe birou'], ['TASTA', 'O apeși pe tastatură'], ['PAROLA', 'Cuvânt secret'], ['ECRAN', 'Pe el vezi imaginile'], ['INTERNET', 'Leagă calculatoarele']],
        ['Calculatoarele înțeleg doar două cifre: 0 și 1.', 'O parolă bună e lungă și nu e un cuvânt din dicționar.', 'Primul calculator ocupa o cameră întreagă și era mai slab decât un telefon de azi.']),
      r('dinozauri', 'Muzeul Dinozaurilor', 'Oase, ouă și amprente', '🦕', 320,
        'Muzeul s-a închis, iar tu ești în sala cu schelete. Paznicul a lăsat <b>{n} probe</b> pentru cine vrea afară.',
        ['count', 'math', 'culture', 'sequence', 'shapes', 'match', 'order', 'logic', 'riddle'],
        sc('panels', ['#d6b370', '#b8955a', '#8b6a3a'], 'tiles', ['#a8a29e', '#57534e'], 'lamp', 'wood', '#16a34a', '#f59e0b', '#7c4a1e', '#94a3b8',
           [['ou', 'Oul de dinozaur'], ['coarne', 'Fosilele'], ['vitrina', 'Vitrina cu dinți'], ['afis', 'Afișul expoziției']]),
        [['OS', 'Din el e făcut scheletul'], ['OU', 'Puiul iese din el'], ['FOSILA', 'Urmă veche în piatră'], ['GHEARA', 'Unghie ascuțită'], ['DINOZAUR', 'Reptilă uriașă de demult'], ['SCHELET', 'Toate oasele la un loc']],
        ['Dinozaurii au trăit pe Pământ de 100 de ori mai mult decât oamenii până acum.', 'Păsările de azi sunt rudele cele mai apropiate ale dinozaurilor.', 'Cel mai mare dinozaur era lung cât trei autobuze puse cap la cap.']),
      r('fabrica', 'Fabrica de Mașini', 'Roboți, benzi și scântei', '🚗', 340,
        'Banda de montaj s-a oprit și poarta halei s-a coborât. <b>Repornește cei {n} roboți</b> ca să iasă și mașina, și tu.',
        ['math', 'sequence', 'count', 'logic', 'order', 'sliders', 'dial', 'shapes', 'weights'],
        sc('metal', ['#9ca3af', '#6b7280', '#4b5563'], 'metal', ['#6b7280', '#374151'], 'neon', 'garage', '#f97316', '#22d3ee', '#7c4a1e', '#9ca3af',
           [['robot', 'Robotul sudor'], ['roata', 'Roata uriașă'], ['panou', 'Panoul benzii'], ['cutii', 'Lăzile cu piese']]),
        [['ROATA', 'Mașina are patru'], ['MOTOR', 'Pune mașina în mișcare'], ['FAR', 'Luminează drumul'], ['VOLAN', 'Îl ține șoferul'], ['CENTURA', 'Te protejează în mașină'], ['ROBOT', 'Mașinărie care lucrează singură']],
        ['Într-o fabrică modernă, o mașină nouă iese de pe bandă la fiecare minut.', 'Roboții sudori lucrează cu scântei atât de puternice încât oamenii poartă mască.', 'Centura de siguranță a salvat mai multe vieți decât orice altă invenție din mașină.']),
      r('planetariu', 'Planetariul', 'Un cer întreg sub cupolă', '🪐', 320,
        'Spectacolul s-a terminat, luminile s-au stins și ușa cupolei e blocată. <b>Găsește cele {n} constelații-cheie</b> ca să ieși.',
        ['count', 'math', 'sequence', 'shapes', 'culture', 'logic', 'match', 'cipher', 'order'],
        sc('night', ['#0f172a', '#1e1b4b', '#0f172a'], 'carpet', ['#312e81', '#1e1b4b'], 'moon', 'metal', '#a855f7', '#38bdf8', '#7c4a1e', '#94a3b8',
           [['glob', 'Globul lunar'], ['ecran', 'Pupitrul de comandă'], ['telescop', 'Luneta'], ['afis', 'Afișul cu planete']], 'night'),
        [['SOARE', 'Steaua noastră'], ['LUNA', 'Satelitul Pământului'], ['STEA', 'Punct de lumină'], ['SATURN', 'Planeta cu inele'], ['RACHETA', 'Zboară în spațiu'], ['ASTRONAUT', 'Om care merge în spațiu']],
        ['Saturn e atât de ușor încât ar pluti pe apă, dacă ar exista un ocean destul de mare.', 'În spațiu nu e nici sus, nici jos — astronauții plutesc.', 'Soarele e atât de mare încât în el ar încăpea un milion de Pământuri.']),
      r('drone', 'Atelierul de Drone', 'Elice, baterii și telecomenzi', '🛸', 320,
        'Drona de test a lovit întrerupătorul ușii. <b>Calibrează cele {n} aparate</b> și ușa se ridică singură.',
        ['math', 'sequence', 'sliders', 'dial', 'count', 'logic', 'shapes', 'order', 'clock'],
        sc('dots', ['#e5e7eb', '#d1d5db', '#9ca3af'], 'metal', ['#6b7280', '#374151'], 'lamp', 'garage', '#ef4444', '#22d3ee', '#7c4a1e', '#9ca3af',
           [['baloane', 'Balonul de test'], ['birou', 'Biroul cu telecomenzi'], ['unelte', 'Uneltele'], ['robot', 'Robotul asistent']]),
        [['ELICE', 'Se învârte și ridică drona'], ['ZBOR', 'Ce face pasărea'], ['CAMERA', 'Filmează de sus'], ['BATERIE', 'Dă energie dronei'], ['SEMNAL', 'Leagă drona de telecomandă'], ['TELECOMANDA', 'Conduci drona cu ea']],
        ['Dronele zboară cu patru elice: două se învârt într-un sens și două în celălalt.', 'Unele drone livrează medicamente în sate greu accesibile.', 'Dronele mari au nevoie de permis de zbor, ca avioanele.']),
      r('mina', 'Mina de Cristale', 'Vagoneți, felinare și strălucire', '⛏️', 340,
        'Un vagonet a blocat galeria de ieșire. Minerii au lăsat <b>{n} probe</b> — rezolvă-le și găsești manivela.',
        ['count', 'math', 'weights', 'sequence', 'shapes', 'logic', 'dial', 'sliders', 'cipher'],
        sc('cave', ['#44403c', '#292524', '#1c1917'], 'stone', ['#44403c', '#1c1917'], 'torches', 'cave', '#a855f7', '#22d3ee', '#7c4a1e', '#78716c',
           [['cristal', 'Cristalele'], ['carucior', 'Vagonetul'], ['unelte', 'Târnăcoapele'], ['lampadar', 'Felinarul minerului']]),
        [['CASCA', 'Apără capul minerului'], ['AUR', 'Metal prețios'], ['TUNEL', 'Drum săpat în munte'], ['MINER', 'Lucrează sub pământ'], ['LOPATA', 'Sapă pământul'], ['CRISTAL', 'Piatră transparentă']],
        ['Cristalele cresc încet, strat cu strat, ca inelele unui copac.', 'Casca de miner are o lampă pentru că sub pământ e beznă totală.', 'Sarea pe care o mâncăm vine tot din mine, săpate în munți de sare.']),
      r('sera', 'Sera Botanistului', 'Sticlă, aburi și plante uriașe', '🌱', 300,
        'Ușa serei se închide automat când e prea cald. <b>Reglează cele {n} aparate</b> ale grădinii și ea se va deschide.',
        ['count', 'math', 'sequence', 'shapes', 'sliders', 'dial', 'match', 'logic', 'riddle'],
        sc('plain', ['#bbf7d0', '#86efac', '#4ade80'], 'tiles', ['#a8a29e', '#57534e'], 'sun', 'glass', '#f97316', '#0ea5e9', '#7c4a1e', '#94a3b8',
           [['planta', 'Planta uriașă'], ['cactus', 'Cactusul'], ['borcan', 'Borcanul cu semințe'], ['cadran', 'Termometrul serei']]),
        [['FRUNZA', 'Verde, pe ramură'], ['RADACINA', 'Crește sub pământ'], ['SEMINTE', 'Din ele răsar plantele'], ['APA', 'Uzi florile cu ea'], ['SOARE', 'Plantele cresc spre el'], ['GHIVECI', 'Casa plantei']],
        ['Într-o seră e cald pentru că sticla lasă lumina să intre, dar nu lasă căldura să iasă.', 'Plantele „respiră” invers față de noi: iau dioxid de carbon și dau oxigen.', 'Unele plante carnivore prind insecte în doar o zecime de secundă.'])
    ] },

    /* ================================================================
       LUMEA 8 — SPORT ȘI JOACĂ
       ================================================================ */
    { id: 'sport', name: 'Sport și Joacă', emoji: '🏆', desc: 'Stadion, patinoar, bazin și tabără', rooms: [
      r('vestiar', 'Vestiarul Stadionului', 'Mingi, tricouri și fluier', '⚽', 300,
        'Meciul începe în cinci minute, dar ușa vestiarului e blocată. Antrenorul a lăsat <b>{n} probe</b> pe tabla cu tactici.',
        ['math', 'count', 'sequence', 'clock', 'shapes', 'logic', 'order', 'match', 'weights'],
        sc('tiles', ['#e5e7eb', '#d1d5db', '#9ca3af'], 'checker', ['#4ade80', '#15803d'], 'lamp', 'metal', '#2563eb', '#f59e0b', '#7c4a1e', '#94a3b8',
           [['mingi', 'Mingile'], ['dulap', 'Dulapul cu echipamente'], ['tabla', 'Tabla cu tactici'], ['ceas', 'Ceasul meciului']]),
        [['GOL', 'Mingea intră în poartă'], ['MINGE', 'O lovești cu piciorul'], ['FLUIER', 'Arbitrul suflă în el'], ['ECHIPA', 'Jucătorii împreună'], ['PORTAR', 'Apără poarta'], ['TRICOU', 'Are un număr pe spate']],
        ['Un jucător de fotbal aleargă într-un meci cam 10 kilometri.', 'Mingea de fotbal are 32 de petice: 12 pentagoane și 20 de hexagoane.', 'Arbitrul ridică cartonașul galben pentru avertisment și roșu pentru eliminare.']),
      r('sala_sport', 'Sala de Sport', 'Coșuri, saltele și frânghii', '🏀', 300,
        'Profesorul de sport a încuiat sala cu tine la strâns mingile. <b>Rezolvă probele</b> ca să afli codul de la ușa de urgență.',
        ['count', 'math', 'sequence', 'shapes', 'logic', 'order', 'weights', 'dial', 'match'],
        sc('panels', ['#fde68a', '#fcd34d', '#f59e0b'], 'planks', ['#d6b370', '#a16207'], 'lamp', 'garage', '#dc2626', '#2563eb', '#a16207', '#94a3b8',
           [['mingi', 'Mingile'], ['tinta', 'Ținta'], ['cadran', 'Cronometrul'], ['cutii', 'Saltelele împăturite']]),
        [['COS', 'Mingea de baschet intră în el'], ['SALT', 'Sari în sus'], ['SALTEA', 'Aterizezi pe ea'], ['FRANGHIE', 'Te cațeri pe ea'], ['ECHIPA', 'Jucătorii împreună'], ['ANTRENOR', 'Conduce antrenamentul']],
        ['După sport, mușchii au nevoie de apă și odihnă ca să crească.', 'Cea mai înaltă săritură la baschet depășește un metru.', 'Încălzirea de dinainte de sport ferește mușchii de întinderi.']),
      r('patinoar', 'Patinoarul', 'Gheață lucioasă și muzică', '⛸️', 320,
        'Luminile patinoarului s-au stins și poarta de sticlă s-a blocat. <b>Rezolvă probele</b> ca să repornești mașina de gheață.',
        ['math', 'count', 'sequence', 'shapes', 'clock', 'logic', 'order', 'sliders', 'riddle'],
        sc('ice', ['#bae6fd', '#7dd3fc', '#38bdf8'], 'ice', ['#e0f2fe', '#bae6fd'], 'neon', 'glass', '#ec4899', '#a855f7', '#7c4a1e', '#94a3b8',
           [['sanie', 'Sania'], ['ecran', 'Tabela de scor'], ['clopot', 'Clopotul de final'], ['valiza', 'Geanta cu patine']]),
        [['PATINE', 'Aluneci cu ele pe gheață'], ['GHEATA', 'Netedă și rece'], ['PUC', 'Discul de la hochei'], ['CROSA', 'Bățul de hochei'], ['PIRUETA', 'Învârtire pe un picior'], ['MANUSI', 'Țin mâinile calde']],
        ['Lama patinei topește puțin gheața sub ea, de aceea aluneci așa de bine.', 'Gheața patinoarului e groasă cam de 3 centimetri.', 'Patinatorii se rotesc mai repede când își strâng brațele la piept.']),
      r('bazin', 'Bazinul de Înot', 'Colaci, cronometre și stropi', '🏊', 300,
        'Salvamarul a închis ușa de la bazin cu tine la duș. <b>Rezolvă probele</b> de pe marginea bazinului ca să ieși uscat.',
        ['count', 'math', 'clock', 'sequence', 'shapes', 'logic', 'order', 'match', 'weights'],
        sc('tiles', ['#7dd3fc', '#38bdf8', '#0ea5e9'], 'water', ['#0284c7', '#075985'], 'sun', 'glass', '#f97316', '#facc15', '#7c4a1e', '#94a3b8',
           [['baloane', 'Colacii'], ['mingi', 'Mingile de apă'], ['semn', 'Indicatorul de adâncime'], ['cadran', 'Cronometrul']]),
        [['APA', 'Înoți în ea'], ['COLAC', 'Te ține la suprafață'], ['DUS', 'Te speli sub el'], ['OCHELARI', 'Îi pui la înot'], ['CULOAR', 'Fâșia ta de bazin'], ['SALVAMAR', 'Are grijă la bazin']],
        ['Nu alerga niciodată pe marginea bazinului: e udă și alunecoasă.', 'Corpul plutește mai ușor în apa sărată de mare decât în piscină.', 'Cea mai rapidă înotătoare e mai lentă decât o rață.']),
      r('arcade', 'Sala de Jocuri', 'Butoane, leduri și scoruri', '🕹️', 320,
        'Ultima fisă s-a blocat în aparat și ușa sălii s-a încuiat. <b>Bate recordurile</b> din cele {n} probe și ieși.',
        ['sequence', 'math', 'count', 'logic', 'order', 'sliders', 'dial', 'shapes', 'cipher'],
        sc('night', ['#1e1b4b', '#0f172a', '#030712'], 'checker', ['#7c3aed', '#312e81'], 'neon', 'garage', '#ec4899', '#22d3ee', '#7c4a1e', '#4b5563',
           [['ecran', 'Ecranul jocului'], ['panou', 'Consola cu butoane'], ['robot', 'Robotul cu premii'], ['mingi', 'Mingile de la coș']], 'night'),
        [['JOC', 'Te distrezi cu el'], ['SCOR', 'Punctele adunate'], ['FISA', 'O bagi în aparat'], ['BUTON', 'Îl apeși'], ['NIVEL', 'Etapa jocului'], ['RECORD', 'Cel mai mare scor']],
        ['Primul joc video, un tenis pe ecran, a apărut acum peste 60 de ani.', 'Aparatele de jocuri vechi aveau ecrane atât de grele încât trebuiau doi oameni să le mute.', 'Ochii obosesc după mult timp la ecran: o pauză la fiecare 20 de minute ajută.']),
      r('camping', 'Tabăra de Vară', 'Corturi, chitară și cer înstelat', '⛺', 300,
        'Poarta taberei se închide la stingere, iar tu ai rămas afară la foc. Cele <b>{n} probe</b> ale monitorului te lasă înapoi.',
        ['count', 'riddle', 'math', 'sequence', 'anagram', 'match', 'logic', 'shapes', 'clock'],
        sc('night', ['#0f172a', '#1e293b', '#14532d'], 'grass', ['#15803d', '#14532d'], 'moon', 'vine', '#f97316', '#facc15', '#7c4a1e', '#78716c',
           [['cort', 'Cortul'], ['foc', 'Focul de tabără'], ['chitara', 'Chitara'], ['borcan', 'Borcanul cu licurici']], 'night'),
        [['CORT', 'Dormi în el în tabără'], ['FOC', 'Îl faci seara'], ['LANTERNA', 'Luminează noaptea'], ['SAC', 'De dormit'], ['CHITARA', 'Cânți la ea lângă foc'], ['BUSOLA', 'Arată nordul']],
        ['Un foc de tabără se face pe pământ curățat, departe de corturi și copaci.', 'Sacul de dormit ține de cald pentru că păstrează aerul încălzit de corp.', 'Departe de oraș se văd de zece ori mai multe stele.']),
      r('balci', 'Parcul de Distracții', 'Roți, tir și vată de zahăr', '🎢', 320,
        'Parcul se închide și ai rămas lângă carusel. <b>Câștigă cele {n} jocuri</b> de la tarabe ca să primești biletul de ieșire.',
        ['count', 'math', 'money', 'sequence', 'shapes', 'logic', 'order', 'dial', 'match'],
        sc('plain', ['#7dd3fc', '#bae6fd', '#fde68a'], 'sand', ['#fde68a', '#d6b370'], 'bulbs', 'gate', '#ec4899', '#22c55e', '#a16207', '#9ca3af',
           [['baloane', 'Baloanele'], ['tinta', 'Ținta de la tir'], ['roata', 'Roata norocului'], ['tort', 'Tortul de la tarabă']]),
        [['BILET', 'Îl cumperi la intrare'], ['ROATA', 'Uriașă, te urcă sus'], ['BALON', 'Zboară dacă îi dai drumul'], ['CARUSEL', 'Se învârte cu căluți'], ['PREMIU', 'Îl câștigi la tir'], ['VATA', 'De zahăr, roz și pufoasă']],
        ['Roata mare se învârte atât de încet încât o tură durează cât un cântec.', 'Vata de zahăr e făcută din zahăr topit tras în fire mai subțiri decât părul.', 'Montagne russe-ul nu are motor pe traseu: coboară doar cu forța gravitației.']),
      r('karting', 'Pista de Karting', 'Cauciucuri, căști și steaguri', '🏎️', 320,
        'Cursa s-a terminat, dar bariera boxelor e coborâtă. <b>Rezolvă probele</b> mecanicilor ca să ridici bariera.',
        ['math', 'sequence', 'count', 'clock', 'order', 'dial', 'sliders', 'logic', 'shapes'],
        sc('metal', ['#9ca3af', '#6b7280', '#4b5563'], 'metal', ['#374151', '#111827'], 'bulbs', 'garage', '#dc2626', '#facc15', '#7c4a1e', '#9ca3af',
           [['roata', 'Roata de rezervă'], ['steag', 'Steagul în carouri'], ['unelte', 'Uneltele mecanicului'], ['cadran', 'Vitezometrul']]),
        [['KART', 'Mașinuță de curse'], ['CASCA', 'Apără capul pilotului'], ['VIRAJ', 'Curbă pe pistă'], ['PISTA', 'Drumul cursei'], ['PILOT', 'Conduce kartul'], ['CAUCIUC', 'Roata e făcută din el']],
        ['Steagul în carouri alb-negru se flutură la finalul cursei.', 'Pe pistă, cel care conduce cel mai lin, nu cel mai brusc, e adesea cel mai rapid.', 'Cauciucurile se încălzesc la cursă și atunci „lipesc” mai bine de asfalt.']),
      r('bowling', 'Sala de Bowling', 'Bile grele și popice', '🎳', 300,
        'Pista s-a blocat cu popicele culcate și ușa nu se deschide până nu e ordine. <b>Rezolvă probele</b> ca să repornești mașina.',
        ['count', 'math', 'sequence', 'shapes', 'weights', 'logic', 'order', 'match', 'money'],
        sc('dots', ['#312e81', '#1e1b4b', '#0f172a'], 'planks', ['#d6b370', '#a16207'], 'neon', 'glass', '#ec4899', '#22d3ee', '#a16207', '#94a3b8',
           [['mingi', 'Bilele'], ['ecran', 'Tabela de scor'], ['semn', 'Indicatorul pistei'], ['tron', 'Scaunul jucătorului']]),
        [['BILA', 'Grea, cu trei găuri'], ['POPIC', 'Cade când e lovit'], ['PISTA', 'Lungă și lucioasă'], ['SCOR', 'Punctele tale'], ['PANTOFI', 'Speciali, de bowling'], ['LOVITURA', 'Toate popicele jos']],
        ['Popicele sunt 10 și stau așezate în triunghi.', 'Bila de bowling poate cântări cât un cățel: până la 7 kilograme.', 'Pista e unsă cu ulei ca bila să alunece drept.']),
      r('dojo', 'Sala de Karate', 'Centuri, saluturi și un gong', '🥋', 320,
        'Antrenamentul s-a terminat, iar ușa de hârtie e blocată de un dulap. <b>Rezolvă probele</b> maestrului cu calm și concentrare.',
        ['math', 'sequence', 'count', 'shapes', 'logic', 'order', 'match', 'cipher', 'riddle'],
        sc('panels', ['#fef3c7', '#fde68a', '#d6b370'], 'planks', ['#d6b370', '#a16207'], 'lamp', 'shoji', '#dc2626', '#1f2937', '#7c2d12', '#94a3b8',
           [['masca', 'Masca de antrenament'], ['steag', 'Steagul dojo-ului'], ['afis', 'Tabelul cu centuri'], ['clopot', 'Gongul']]),
        [['KIMONO', 'Haina albă de karate'], ['CENTURA', 'Arată nivelul'], ['SALUT', 'Îl faci la început'], ['MAESTRU', 'Profesorul de karate'], ['LOVITURA', 'Cu pumnul sau piciorul'], ['ECHILIBRU', 'Nu cazi']],
        ['În karate, centura neagră înseamnă că abia acum începi să înveți cu adevărat.', 'Cuvântul „karate” înseamnă „mână goală”: se luptă fără arme.', 'Salutul de la începutul antrenamentului e semn de respect, nu de supunere.'])
    ] },

    /* ================================================================
       LUMEA 9 — LUMI STRĂVECHI
       ================================================================ */
    { id: 'stravechi', name: 'Lumi Străvechi', emoji: '🏛️', desc: 'Daci, romani, vikingi și samurai', rooms: [
      r('cetate', 'Cetatea Dacică', 'Ziduri de piatră și stindarde', '🛡️', 320,
        'Poarta cetății s-a închis la apusul soarelui. Străjerii au lăsat <b>{n} probe</b> pentru cine vrea să iasă înainte de zori.',
        ['math', 'count', 'shapes', 'sequence', 'cipher', 'logic', 'order', 'weights', 'riddle'],
        sc('stone', ['#78716c', '#57534e', '#44403c'], 'stone', ['#57534e', '#292524'], 'torches', 'gate', '#dc2626', '#fbbf24', '#7c4a1e', '#9ca3af',
           [['scut', 'Scutul dacic'], ['steag', 'Stindardul cu lup'], ['cufar', 'Cufărul cetății'], ['foc', 'Focul străjerilor']]),
        [['ZID', 'Apără cetatea'], ['LUP', 'Pe steagul dacilor'], ['SCUT', 'Te apără de lovituri'], ['POARTA', 'Intrarea cetății'], ['CETATE', 'Oraș cu ziduri'], ['STRAJER', 'Păzește poarta']],
        ['Steagul dacilor avea cap de lup și corp de șarpe și șuiera în vânt.', 'Zidurile cetăților dacice erau făcute din două rânduri de piatră cu pământ între ele.', 'Cetățile dacice erau construite pe dealuri, ca dușmanii să fie văzuți de departe.']),
      r('villa', 'Villa Romană', 'Mozaicuri, amfore și o fântână', '🏛️', 320,
        'Stăpânul vilei a plecat la forum și sclavii au închis porțile. Rezolvă <b>{n} probe</b> lângă fântână ca să găsești cheia.',
        ['math', 'shapes', 'count', 'sequence', 'culture', 'logic', 'order', 'match', 'cipher'],
        sc('panels', ['#fde68a', '#fcd34d', '#d6b370'], 'tiles', ['#d6d3d1', '#78716c'], 'sun', 'stone', '#b91c1c', '#0ea5e9', '#a16207', '#fbbf24',
           [['statuie', 'Statuia'], ['vaza', 'Amfora'], ['fantana', 'Fântâna'], ['harta', 'Harta imperiului']]),
        [['ROMA', 'Orașul de pe șapte coline'], ['TOGA', 'Haina romanilor'], ['AMFORA', 'Vas pentru ulei și vin'], ['MOZAIC', 'Podea din pietricele colorate'], ['FORUM', 'Piața orașului roman'], ['LEGIUNE', 'Armata romană']],
        ['Romanii aveau apă caldă în case și încălzire prin podea, acum 2000 de ani.', 'Drumurile romane erau atât de bine făcute încât unele se folosesc și azi.', 'Cifrele romane (I, V, X) se mai văd pe ceasuri și pe monumente.']),
      r('vikingi', 'Corabia Vikingilor', 'Scuturi rotunde și un cap de dragon', '⚔️', 320,
        'Furtuna a împins corabia în ceață și cabina e închisă. <b>Rezolvă probele</b> vikingilor ca să prinzi vâslele.',
        ['math', 'count', 'weights', 'sequence', 'cipher', 'logic', 'order', 'shapes', 'riddle'],
        sc('planks', ['#6b4423', '#4a2e14', '#2f1b0c'], 'planks', ['#5c3a1e', '#2f1b0c'], 'moon', 'wood', '#dc2626', '#fbbf24', '#7c4a1e', '#9ca3af',
           [['scut', 'Scutul rotund'], ['roata', 'Timona'], ['butoi', 'Butoiul cu provizii'], ['ancora', 'Ancora']], 'night'),
        [['SCUT', 'Rotund, de lemn'], ['VASLA', 'Împinge corabia'], ['COIF', 'Apără capul'], ['MARE', 'Apă sărată, cât vezi'], ['DRAGON', 'Capul de la prova'], ['NAVIGATOR', 'Găsește drumul pe mare']],
        ['Coifurile vikingilor nu aveau coarne — asta e o invenție din teatru.', 'Corăbiile vikingilor erau atât de ușoare încât puteau fi trase pe uscat.', 'Vikingii au ajuns în America cu 500 de ani înaintea lui Columb.']),
      r('samurai', 'Castelul Samurailor', 'Măști, săbii și hârtie de orez', '🏯', 340,
        'Shogunul a plecat la ceai și ușa glisantă a fost proptită. <b>Rezolvă probele</b> cu răbdare de samurai.',
        ['math', 'sequence', 'count', 'shapes', 'logic', 'order', 'cipher', 'match', 'clock'],
        sc('panels', ['#b91c1c', '#991b1b', '#7f1d1d'], 'planks', ['#a16207', '#713f12'], 'candles', 'shoji', '#facc15', '#1f2937', '#7c2d12', '#94a3b8',
           [['masca', 'Masca de samurai'], ['steag', 'Steagul clanului'], ['vaza', 'Vaza cu flori de cireș'], ['tablou', 'Tabloul cu munți']]),
        [['SABIE', 'Arma samuraiului'], ['ONOARE', 'Ce apără samuraiul'], ['CASTEL', 'Casa shogunului'], ['ARMURA', 'Îl apără în luptă'], ['CIRES', 'Copac cu flori roz'], ['CALIGRAFIE', 'Scris frumos cu pensula']],
        ['Săbiile samurailor erau făcute din oțel îndoit de mii de ori.', 'Podelele castelelor japoneze scârțâiau special, ca să se audă cine se apropie.', 'Samuraii învățau și poezie și caligrafie, nu doar lupta.']),
      r('templu_grec', 'Templul Grecesc', 'Coloane albe și măsline', '🏺', 320,
        'Preoții au închis templul la apus. Statuile păzesc <b>{n} probe</b> — rezolvă-le și ușa de bronz se deschide.',
        ['math', 'shapes', 'count', 'sequence', 'logic', 'culture', 'order', 'cipher', 'riddle'],
        sc('panels', ['#f5f5f4', '#e7e5e4', '#7dd3fc'], 'tiles', ['#e7e5e4', '#a8a29e'], 'sun', 'stone', '#0ea5e9', '#fbbf24', '#a16207', '#fbbf24',
           [['statuie', 'Statuia zeiței'], ['vaza', 'Amfora pictată'], ['harta', 'Harta insulelor'], ['cufar', 'Cufărul cu ofrande']]),
        [['ZEU', 'Trăia pe Olimp'], ['COLOANA', 'Ține acoperișul templului'], ['MASLINA', 'Fruct mic din care se face ulei'], ['OLIMP', 'Muntele zeilor'], ['TEATRU', 'Loc pentru spectacole'], ['MARATON', 'Alergare foarte lungă']],
        ['Jocurile Olimpice au început în Grecia acum aproape 2800 de ani.', 'Teatrele grecești erau construite așa încât o șoaptă se auzea și pe ultimul rând.', 'Multe cuvinte de azi, ca „matematică” sau „telefon”, vin din limba greacă.']),
      r('preistorie', 'Peștera Preistorică', 'Picturi pe pereți și un foc', '🦣', 320,
        'Un mamut a blocat intrarea peșterii cu o stâncă. Picturile de pe pereți ascund <b>{n} probe</b> — rezolvă-le și găsești tunelul.',
        ['count', 'math', 'shapes', 'sequence', 'match', 'logic', 'order', 'riddle', 'weights'],
        sc('cave', ['#a16207', '#78350f', '#451a03'], 'stone', ['#78350f', '#451a03'], 'torches', 'cave', '#dc2626', '#fbbf24', '#7c4a1e', '#78716c',
           [['foc', 'Focul'], ['coarne', 'Coarnele de mamut'], ['unelte', 'Uneltele de piatră'], ['ou', 'Oul uriaș']]),
        [['FOC', 'Primii oameni l-au descoperit'], ['MAMUT', 'Elefant păros de demult'], ['PIATRA', 'Din ea se făceau unelte'], ['SULITA', 'Băț cu vârf ascuțit'], ['PESTERA', 'Casa oamenilor de demult'], ['PICTURA', 'Desen pe perete']],
        ['Cele mai vechi picturi din peșteri au peste 30.000 de ani.', 'Primii oameni făceau focul frecând două bețe până se aprindeau.', 'Mamuții aveau blană lungă și trăiau pe vremea când Pământul era acoperit de gheață.']),
      r('bazar', 'Bazarul Otoman', 'Covoare, mătase și cafea', '🧿', 320,
        'Bazarul s-a închis cu perdele grele. Negustorii au lăsat <b>{n} probe</b> pe rafturi — rezolvă-le ca să afli ieșirea.',
        ['money', 'math', 'count', 'weights', 'match', 'order', 'sequence', 'logic', 'shapes'],
        sc('dots', ['#0e7490', '#155e75', '#164e63'], 'carpet', ['#b91c1c', '#7f1d1d'], 'candles', 'curtain', '#fbbf24', '#f97316', '#92400e', '#fbbf24',
           [['vaza', 'Urciorul de aramă'], ['ceainic', 'Ibricul de cafea'], ['cufar', 'Cufărul cu mătase'], ['raft', 'Raftul cu mirodenii']]),
        [['BAZAR', 'Piață acoperită'], ['COVOR', 'Țesut de mână'], ['CAFEA', 'Băutură neagră'], ['MATASE', 'Material moale și lucios'], ['FELINAR', 'Lampă colorată'], ['NEGUSTOR', 'Vinde în bazar']],
        ['Marele Bazar din Istanbul are peste 4000 de prăvălii.', 'Cafeaua a ajuns în Europa prin negustorii din Imperiul Otoman.', 'Covoarele orientale au modele care spun povești despre satul unde au fost țesute.']),
      r('manastire', 'Scriptoriul Mănăstirii', 'Pergamente, pene și lumânări', '📜', 320,
        'Călugărul copist a plecat la slujbă și a stins lumânările. <b>Descifrează cele {n} manuscrise</b> ca să ieși din scriptoriu.',
        ['cipher', 'anagram', 'proverb', 'math', 'count', 'order', 'logic', 'sequence', 'riddle'],
        sc('stone', ['#78716c', '#57534e', '#44403c'], 'planks', ['#7c4a1e', '#3f2107'], 'candles', 'wood', '#b91c1c', '#fbbf24', '#7c4a1e', '#94a3b8',
           [['birou', 'Pupitrul cu manuscrise'], ['raft', 'Raftul cu cărți vechi'], ['clopot', 'Clopotul'], ['harta', 'Harta veche']]),
        [['PANA', 'Se scria cu ea'], ['CARTE', 'Are pagini scrise'], ['LITERA', 'Semn din alfabet'], ['CLOPOT', 'Sună în turn'], ['PERGAMENT', 'Hârtie din piele'], ['CALUGAR', 'Copia cărțile de mână']],
        ['O carte copiată de mână putea dura un an întreg.', 'Cerneala veche se făcea din gogoși de stejar și fier.', 'Prima literă din pagină era desenată mare și colorată — se numea „inițială”.']),
      r('far', 'Farul Vechi', 'Scări în spirală și o lumină', '🗼', 320,
        'Paznicul farului a plecat cu barca și a lăsat ușa de fier încuiată. <b>Aprinde lumina</b> rezolvând cele {n} probe.',
        ['math', 'count', 'sequence', 'clock', 'logic', 'dial', 'sliders', 'shapes', 'riddle'],
        sc('stone', ['#e7e5e4', '#d6d3d1', '#a8a29e'], 'planks', ['#7c4a1e', '#3f2107'], 'windows', 'metal', '#dc2626', '#0ea5e9', '#7c4a1e', '#9ca3af',
           [['telescop', 'Luneta'], ['ancora', 'Ancora'], ['harta', 'Harta coastei'], ['lampadar', 'Lampa farului']], 'sea'),
        [['FAR', 'Luminează corăbiile'], ['VAL', 'Se sparge de stânci'], ['BARCA', 'Plutește pe apă'], ['STANCA', 'Piatră mare la mal'], ['LUMINA', 'Farul o trimite departe'], ['SPIRALA', 'Forma scării din far']],
        ['Lumina unui far se vede de la peste 30 de kilometri.', 'Fiecare far clipește într-un ritm propriu, ca marinarii să știe unde sunt.', 'Farurile de demult ardeau ulei de balenă sau lemne.']),
      r('maya', 'Templul Maya', 'Trepte, jad și un calendar de piatră', '🗿', 340,
        'Poarta de piatră a templului a coborât în urma ta. Calendarul de pe perete ascunde <b>{n} probe</b> — rezolvă-le și piatra urcă.',
        ['math', 'sequence', 'count', 'shapes', 'cipher', 'logic', 'order', 'match', 'weights'],
        sc('stone', ['#4d7c0f', '#3f6212', '#1a2e05'], 'stone', ['#57534e', '#292524'], 'torches', 'stone', '#16a34a', '#fbbf24', '#7c4a1e', '#78716c',
           [['masca', 'Masca de jad'], ['statuie', 'Idolul de piatră'], ['cristal', 'Cristalele'], ['calendar', 'Calendarul de piatră']]),
        [['JAD', 'Piatră verde prețioasă'], ['TREAPTA', 'Urci pe ea'], ['JUNGLA', 'Pădure deasă și caldă'], ['TEMPLU', 'Clădire sfântă'], ['CACAO', 'Din el se face ciocolata'], ['PIRAMIDA', 'Templu cu trepte']],
        ['Mayașii au inventat cifra zero înaintea multor popoare.', 'Boabele de cacao erau folosite de mayași ca bani.', 'Calendarul mayaș era atât de precis încât anul avea exact 365 de zile.'])
    ] },

    /* ================================================================
       LUMEA 10 — MISTER ȘI AVENTURĂ
       ================================================================ */
    { id: 'aventura', name: 'Mister și Aventură', emoji: '🕵️', desc: 'Case bântuite, epave și baze secrete', rooms: [
      r('bantuita', 'Casa Bântuită', 'Scârțâituri și portrete cu ochi', '👻', 340,
        'Ușa s-a trântit singură, iar ceasul din hol s-a oprit. Fantomele sunt prietenoase — dar cer <b>{n} probe</b> ca să te lase să pleci.',
        ['riddle', 'count', 'math', 'sequence', 'cipher', 'logic', 'clock', 'order', 'anagram'],
        sc('panels', ['#4c1d95', '#3b0764', '#1e0a3c'], 'planks', ['#3b0764', '#1e0a3c'], 'candles', 'wood', '#a855f7', '#22c55e', '#4c1d95', '#78716c',
           [['portret', 'Portretul cu ochi vii'], ['panza', 'Pânza de păianjen'], ['oglinda', 'Oglinda aburită'], ['ceas', 'Ceasul oprit']], 'night'),
        [['FANTOMA', 'Plutește prin casă'], ['PAIANJEN', 'Țese pânze'], ['SCARA', 'Scârțâie noaptea'], ['POD', 'Camera de sub acoperiș'], ['LUMANARE', 'Dă lumină tremurată'], ['CEATA', 'Alb și des, nu vezi prin el']],
        ['Casele vechi scârțâie noaptea pentru că lemnul se strânge când se răcește.', 'Păianjenii de casă sunt folositori: mănâncă muștele și țânțarii.', 'Multe „fantome” din povești erau, de fapt, curenți de aer și umbre.']),
      r('catacombe', 'Catacombele', 'Tuneluri, torțe și lăzi vechi', '🕯️', 340,
        'Grilajul de fier a căzut în urma ta. Tunelurile au <b>{n} semne</b> lăsate de exploratori — ele duc la scara de ieșire.',
        ['math', 'count', 'sequence', 'cipher', 'logic', 'order', 'shapes', 'dial', 'riddle'],
        sc('stone', ['#44403c', '#292524', '#1c1917'], 'stone', ['#292524', '#0c0a09'], 'torches', 'gate', '#f97316', '#a855f7', '#57534e', '#78716c',
           [['cufar', 'Cufărul vechi'], ['statuie', 'Statuia'], ['borcan', 'Borcanul cu ulei'], ['cutii', 'Lăzile vechi']]),
        [['TUNEL', 'Drum pe sub pământ'], ['TORTA', 'Luminează tunelul'], ['SCARA', 'Urcă spre ieșire'], ['CHEIE', 'Deschide grilajul'], ['LABIRINT', 'Drumuri încâlcite'], ['EXPLORATOR', 'Descoperă locuri noi']],
        ['Sub Paris sunt sute de kilometri de tuneluri vechi.', 'Într-un labirint ieși sigur dacă ții mereu mâna dreaptă pe perete.', 'Torțele de demult erau bețe înfășurate în cârpe înmuiate în smoală.']),
      r('avion', 'Avionul Prăbușit', 'Nisip, valize și un radar', '✈️', 340,
        'Avionul a aterizat forțat în deșert și trapa s-a blocat. <b>Repornește radarul</b> în cele {n} probe ca să trimiți semnalul.',
        ['math', 'sequence', 'count', 'dial', 'sliders', 'logic', 'order', 'cipher', 'clock'],
        sc('metal', ['#9ca3af', '#6b7280', '#4b5563'], 'sand', ['#fde68a', '#d6b370'], 'sun', 'hatch', '#f97316', '#22d3ee', '#7c4a1e', '#9ca3af',
           [['valiza', 'Valiza'], ['panou', 'Panoul de bord'], ['ecran', 'Radarul'], ['cutii', 'Lăzile cu provizii']]),
        [['ARIPA', 'Avionul are două'], ['PILOT', 'Conduce avionul'], ['RADAR', 'Vede avioanele pe ecran'], ['ZBOR', 'Călătorie prin aer'], ['PARASUTA', 'Te coboară încet'], ['CENTURA', 'O legi la decolare']],
        ['Avionul se ridică pentru că aerul trece mai repede pe deasupra aripii decât pe dedesubt.', 'Cutia neagră a avionului e, de fapt, portocalie — ca să fie găsită ușor.', 'La 10 kilometri înălțime, afară sunt minus 50 de grade.']),
      r('baza', 'Baza Secretă', 'Seifuri, lasere și parole', '🕶️', 340,
        'Alarma a blocat toate ușile bazei. Agentul secret a lăsat <b>{n} probe</b> — doar cine le rezolvă primește codul seifului.',
        ['cipher', 'math', 'sequence', 'logic', 'count', 'dial', 'sliders', 'order', 'anagram'],
        sc('metal', ['#334155', '#1e293b', '#0f172a'], 'metal', ['#334155', '#0f172a'], 'neon', 'vault', '#ef4444', '#22d3ee', '#7c4a1e', '#64748b',
           [['seif', 'Seiful'], ['ecran', 'Monitorul de supraveghere'], ['panou', 'Panoul cu butoane'], ['robot', 'Robotul de pază']]),
        [['AGENT', 'Spion secret'], ['SEIF', 'Cutie de fier cu cifru'], ['LASER', 'Rază de lumină roșie'], ['PAROLA', 'Cuvânt secret'], ['CAMERA', 'Filmează tot'], ['MISIUNE', 'Sarcina agentului']],
        ['Cel mai sigur seif se deschide doar cu cifru, cheie și amprentă la un loc.', 'Razele laser pot fi văzute numai dacă în aer e praf sau fum.', 'Codurile secrete existau și în vechime: Cezar muta literele cu trei poziții.']),
      r('mlastina', 'Mlaștina Cețoasă', 'Broaște, ceață și o barcă', '🐊', 340,
        'Barca s-a împotmolit în nămol și ceața a acoperit drumul. Cele <b>{n} probe</b> de pe mal îți arată ieșirea din mlaștină.',
        ['count', 'riddle', 'math', 'sequence', 'logic', 'match', 'shapes', 'order', 'weights'],
        sc('leaves', ['#1a2e05', '#14532d', '#052e16'], 'water', ['#3f6212', '#1a2e05'], 'moon', 'vine', '#84cc16', '#f97316', '#5c3a1e', '#78716c',
           [['cutii', 'Lăzile din colibă'], ['foc', 'Focul'], ['borcan', 'Borcanul cu licurici'], ['ancora', 'Ancora bărcii']], 'night'),
        [['NAMOL', 'Noroi moale și lipicios'], ['CEATA', 'Nor la nivelul pământului'], ['BROASCA', 'Orăcăie seara'], ['BARCA', 'Plutește pe apă'], ['CROCODIL', 'Reptilă cu dinți mari'], ['TANTAR', 'Bâzâie și înțeapă']],
        ['Ceața e un nor care s-a lăsat până la pământ.', 'Crocodilii pot sta sub apă mai bine de o oră fără să respire.', 'Mlaștinile curăță apa ca un filtru uriaș.']),
      r('epava', 'Epava Scufundată', 'Perle, alge și o timonă ruptă', '🐚', 340,
        'Ai coborât în epavă după comoară, dar trapa s-a închis. <b>Rezolvă probele</b> ascunse în cabină înainte să se termine aerul.',
        ['count', 'math', 'money', 'sequence', 'cipher', 'logic', 'shapes', 'order', 'weights'],
        sc('plain', ['#0c4a6e', '#075985', '#082f49'], 'sand', ['#0e7490', '#164e63'], 'none', 'hatch', '#fbbf24', '#22d3ee', '#5c3a1e', '#78716c',
           [['cufar', 'Cufărul cu perle'], ['ancora', 'Ancora'], ['roata', 'Timona ruptă'], ['butoi', 'Butoiul']]),
        [['PERLA', 'Se găsește în scoică'], ['ALGA', 'Plantă verde din mare'], ['EPAVA', 'Corabie scufundată'], ['CARACATITA', 'Are opt brațe'], ['SCAFANDRU', 'Înoată cu butelie'], ['COMOARA', 'Cufăr cu aur']],
        ['O perlă crește în scoică în jurul unui fir de nisip, timp de ani de zile.', 'Scafandrii urcă la suprafață încet, altfel li se face rău.', 'Sub apă, sunetul merge de patru ori mai repede decât în aer.']),
      r('hotel', 'Hotelul Părăsit', 'Chei ruginite și un lift vechi', '🛎️', 340,
        'Liftul s-a oprit la etajul 13 și ușa camerei s-a încuiat. Recepționerul-fantomă îți cere <b>{n} probe</b> pentru cheie.',
        ['clock', 'math', 'count', 'sequence', 'riddle', 'logic', 'order', 'cipher', 'match'],
        sc('panels', ['#7f1d1d', '#450a0a', '#1c1917'], 'carpet', ['#7f1d1d', '#450a0a'], 'lamp', 'elevator', '#fbbf24', '#22c55e', '#5c3a1e', '#9ca3af',
           [['clopot', 'Clopoțelul de la recepție'], ['valiza', 'Valiza uitată'], ['cheie', 'Cheia camerei 13'], ['portret', 'Portretul directorului']]),
        [['CHEIE', 'Deschide camera'], ['LIFT', 'Te urcă la etaj'], ['ETAJ', 'Nivel al clădirii'], ['HOL', 'Coridor lung'], ['RECEPTIE', 'Unde primești cheia'], ['OASPETE', 'Cel care stă la hotel']],
        ['Multe hoteluri sar peste etajul 13 pentru că unii oameni cred că aduce ghinion.', 'Dacă liftul se oprește, apasă butonul de alarmă și așteaptă — nu forța ușile.', 'Cel mai vechi hotel din lume, în Japonia, funcționează de 1300 de ani.']),
      r('metrou', 'Tunelul Metroului', 'Șine, hărți și lumini de neon', '🚇', 320,
        'Ultimul tren a plecat și grilajul stației s-a coborât. Cele <b>{n} probe</b> din stație îți spun codul ieșirii de urgență.',
        ['math', 'clock', 'sequence', 'count', 'order', 'logic', 'match', 'cipher', 'shapes'],
        sc('tiles', ['#e5e7eb', '#d1d5db', '#9ca3af'], 'metal', ['#374151', '#111827'], 'neon', 'metal', '#2563eb', '#f59e0b', '#7c4a1e', '#9ca3af',
           [['semn', 'Indicatorul stației'], ['semafor', 'Semaforul liniei'], ['harta', 'Harta liniilor'], ['cutii', 'Lăzile de întreținere']]),
        [['SINA', 'Pe ea merge trenul'], ['STATIE', 'Locul unde oprește metroul'], ['PERON', 'Aștepți trenul pe el'], ['TUNEL', 'Drum pe sub oraș'], ['BILET', 'Îl validezi la intrare'], ['LINIE', 'Traseul metroului']],
        ['Metroul din București are peste 60 de stații.', 'Linia galbenă de pe peron arată până unde e sigur să stai.', 'Primul metrou din lume a pornit la Londra, cu trenuri cu aburi.']),
      r('ceara', 'Muzeul de Ceară', 'Figuri care par vii', '🕴️', 320,
        'Luminile s-au stins și figurile de ceară par că se mișcă. Paznicul a lăsat <b>{n} probe</b> — rezolvă-le și găsești ieșirea.',
        ['count', 'riddle', 'math', 'sequence', 'match', 'logic', 'order', 'shapes', 'culture'],
        sc('panels', ['#7c3aed', '#5b21b6', '#3b0764'], 'carpet', ['#b91c1c', '#7f1d1d'], 'lamp', 'wood', '#fbbf24', '#ec4899', '#5c3a1e', '#fbbf24',
           [['statuie', 'Statuia de ceară'], ['portret', 'Portretul'], ['vitrina', 'Vitrina'], ['tron', 'Tronul regelui']]),
        [['CEARA', 'Din ea se fac lumânări'], ['STATUIE', 'Om făcut din piatră sau ceară'], ['MUZEU', 'Loc cu obiecte vechi'], ['PAZNIC', 'Are grijă noaptea'], ['MASCA', 'Ascunde fața'], ['VITRINA', 'Dulap de sticlă']],
        ['Figurile de ceară au fire de păr adevărate, puse unul câte unul.', 'Ceara se topește la temperatură mică, de aceea muzeele sunt mereu răcoroase.', 'Primul muzeu de ceară a fost deschis la Londra acum aproape 200 de ani.']),
      r('detectiv', 'Biroul Detectivului', 'Lupă, dosare și o hartă cu ace', '🔍', 340,
        'Detectivul a plecat pe urmele unui hoț și a încuiat biroul. <b>Rezolvă cele {n} indicii</b> de pe hartă ca să afli codul.',
        ['logic', 'cipher', 'math', 'sequence', 'count', 'order', 'match', 'anagram', 'riddle'],
        sc('panels', ['#a8a29e', '#78716c', '#57534e'], 'planks', ['#7c4a1e', '#3f2107'], 'lamp', 'wood', '#dc2626', '#f59e0b', '#7c4a1e', '#94a3b8',
           [['birou', 'Biroul cu dosare'], ['harta', 'Harta cu ace'], ['seif', 'Seiful'], ['dulapior', 'Dulăpiorul cu dosare']]),
        [['LUPA', 'Mărește lucrurile mici'], ['URMA', 'Semn lăsat de hoț'], ['DOSAR', 'Hârtii despre un caz'], ['INDICIU', 'Te ajută să rezolvi cazul'], ['AMPRENTA', 'Urma degetului'], ['DETECTIV', 'Rezolvă mistere']],
        ['Nu există doi oameni cu aceleași amprente, nici măcar gemenii.', 'Un detectiv bun observă lucrurile mici: noroiul de pe pantofi, un nasture lipsă.', 'Lupa mărește pentru că lentila ei e bombată și îndoaie lumina.'])
    ] }
  ];

  /* ------------------------------------------------------------------
     înregistrare: scene, cuvinte, curiozități, lista plată de camere
     ------------------------------------------------------------------ */
  var rooms = [];
  WORLDS.forEach(function (w, wi) {
    if (!w.rooms) return;
    w.rooms.forEach(function (room) {
      room.theme = room.id;
      room.world = wi;
      global.SceneGen.register(room.id, room.scene);
      global.DATA.CUVINTE[room.id] = room.words;
      global.DATA.CURIOZITATI[room.id] = room.facts;
      rooms.push(room);
    });
  });

  global.Worlds = { list: WORLDS, rooms: rooms };
})(window);
